### ISSUE TITLE
monitor scale event

### ISSUE THREAD

**Issue by yanglei629** [oxyplot/oxyplot#1892] opened 2022-05-26 14:22 UTC
Hi, i use customer draggable annotation in oxyplot,it works well in same size.But when i scale the oxyplot size,the point does not locate in correct position.

##For Example
the x is about 30 and y is about -10.
![image](https://user-images.githubusercontent.com/81857996/170505461-8014ef55-a26d-4a96-907d-d7d82eb39eaa.png)

when i maxium the window
the x change to 25 and the y change to 0.
![image](https://user-images.githubusercontent.com/81857996/170505930-e22e0d8a-e391-4667-aa56-02ad7e0b2803.png)

Platform:
.NET version:4.8

### Expected behaviour
the point positon change correctly with its coordinate.

### Actual behaviour
It seems that the point keep his relative screen position,so the coordite is not correct.So i should konw the window scale event and translate the position by its coordinate.

**Comment by VisualMelon** [comment] 2022-05-26 14:37
This is all down to how the annotation is implemented: it seems to be storing its location in screen space, not data-space.

How is the annotation implemented?

**Comment by yanglei629** [comment] 2022-05-26 14:46
Hi,i edit the annotation in your solution which you give me before.I just use the CustomerAnnotation.class,which base on your CursorInfoAnnotation.


##The Code

using OxyPlot;
using OxyPlot.Annotations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OxyPlotDemo
{
    public class CursorPair
    {
        public CursorPair(CursorAnnotation low, CursorAnnotation high)
        {
            Low = low ?? throw new ArgumentNullException(nameof(low));
            High = high ?? throw new ArgumentNullException(nameof(high));
        }

        public CursorAnnotation Low { get; }
        public CursorAnnotation High { get; }

        public bool AnyOn => Low.IsOn || High.IsOn;

        public void GetInfo(out double low, out double high, out double delta)
        {
            low = Low.Position;
            high = High.Position;
            delta = high - low;
        }
    }

    public class CursorInfoAnnotation : Annotation
    {
        private List<CursorPair> Pairs { get; } = new List<CursorPair>();

        public ScreenPoint Position { get; set; } = new ScreenPoint(50, 50);
        public HorizontalAlignment HorizontalAlignment { get; set; } = HorizontalAlignment.Left;
        public VerticalAlignment VerticalAlignment { get; set; } = VerticalAlignment.Top;
        public double Width { get; } = 200;

        public void AddPair(CursorAnnotation low, CursorAnnotation high)
        {
            Pairs.Add(new CursorPair(low, high));
        }

        private int OnCount => Pairs.Count(p => p.AnyOn);

        private OxyRect Bounds { get; set; }

        public CursorInfoAnnotation()
        {
            this.MouseDown += CursorInfoAnnotation_MouseDown;
            this.MouseUp += CursorInfoAnnotation_MouseUp;
            this.MouseMove += CursorInfoAnnotation_MouseMove;
        }

        public override void Render(IRenderContext rc)
        {
            int on = OnCount;
            if (on == 0)
                return;

            var subHeight = rc.MeasureText("0123456789").Height + 2;
            var subWidth = Width / 3;

            var height = subHeight * (on + 1);

            var x = Position.X + (Sign(HorizontalAlignment) + 1) * Width / 2;
            var y = Position.Y + (Sign(VerticalAlignment) + 1) * height / 2;
            var topLeft = new ScreenPoint(x, y);
            Bounds = new OxyRect(topLeft, new OxySize(Width, height));

            rc.DrawRectangle(Bounds, OxyColor.FromAColor(128, OxyColors.LightSteelBlue), OxyColors.Black, 1, EdgeRenderingMode.Automatic);

            rc.DrawText(new ScreenPoint(x + subWidth * 0.5, y + subHeight * 0.5), "Low", OxyColors.Black, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);
            rc.DrawText(new ScreenPoint(x + subWidth * 1.5, y + subHeight * 0.5), "High", OxyColors.Black, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);
            rc.DrawText(new ScreenPoint(x + subWidth * 2.5, y + subHeight * 0.5), "Delta", OxyColors.Black, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);

            foreach (var p in Pairs.Where(p => p.AnyOn))
            {
                y += subHeight;
                p.GetInfo(out double low, out double high, out double delta);

                if (!double.IsNaN(low))
                    rc.DrawText(new ScreenPoint(x + subWidth * 0.5, y + subHeight * 0.5), low.ToString("G5"), p.Low.Color, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);
                if (!double.IsNaN(high))
                    rc.DrawText(new ScreenPoint(x + subWidth * 1.5, y + subHeight * 0.5), high.ToString("G5"), p.High.Color, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);
                if (!double.IsNaN(delta))
                    rc.DrawText(new ScreenPoint(x + subWidth * 2.5, y + subHeight * 0.5), delta.ToString("G5"), p.Low.Color, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);
            }
        }

        protected override HitTestResult HitTestOverride(HitTestArguments args)
        {
            if (Bounds.Contains(args.Point))
            {
                return new HitTestResult(this, args.Point);
            }
            return null;
        }

        private bool moused = false;
        private ScreenVector mouseOffset;

        private void CursorInfoAnnotation_MouseMove(object sender, OxyMouseEventArgs e)
        {
            if (moused && e.Position.X >= 0 && e.Position.Y >= 0 && e.Position.X < PlotModel.Width && e.Position.Y < PlotModel.Height)
            {
                Position = e.Position - mouseOffset;
                PlotModel.InvalidatePlot(false);
            }
        }

        private void CursorInfoAnnotation_MouseUp(object sender, OxyMouseEventArgs e)
        {
            moused = false;
        }

        private void CursorInfoAnnotation_MouseDown(object sender, OxyMouseDownEventArgs e)
        {
            if (e.ChangedButton == OxyMouseButton.Left)
            {
                moused = true;
                mouseOffset = e.Position - Position;
                e.Handled = true;
            }
        }

        private int Sign(HorizontalAlignment horizontalAlignment)
        {
            switch (horizontalAlignment)
            {
                case HorizontalAlignment.Left:
                    return -1;
                case HorizontalAlignment.Center:
                    return 0;
                case HorizontalAlignment.Right:
                    return +1;
                default:
                    throw new ArgumentException(nameof(horizontalAlignment));
            }
        }

        private int Sign(VerticalAlignment verticalAlignment)
        {
            switch (verticalAlignment)
            {
                case VerticalAlignment.Top:
                    return -1;
                case VerticalAlignment.Middle:
                    return 0;
                case VerticalAlignment.Bottom:
                    return +1;
                default:
                    throw new ArgumentException(nameof(verticalAlignment));
            }
        }
    }


    public class CustomAnnotation : Annotation
    {
        //private List<CursorPair> Pairs { get; } = new List<CursorPair>();

        public double X { get; set; }
        public double Y { get; set; }
        public ScreenPoint Position { get; set; }

        public string Label { get; set; }
        public bool initialized { get; set; } = false;
        public HorizontalAlignment HorizontalAlignment { get; set; } = HorizontalAlignment.Left;
        public VerticalAlignment VerticalAlignment { get; set; } = VerticalAlignment.Top;
        public double Width { get; } = 200;

        //public void AddPair(CursorAnnotation low, CursorAnnotation high)
        //{
        //    Pairs.Add(new CursorPair(low, high));
        //}

        //private int OnCount => Pairs.Count(p => p.AnyOn);

        private OxyRect Bounds { get; set; }

        public CustomAnnotation()
        {
            this.MouseDown += CursorInfoAnnotation_MouseDown;
            this.MouseUp += CursorInfoAnnotation_MouseUp;
            this.MouseMove += CursorInfoAnnotation_MouseMove;

            Position = new ScreenPoint(X, Y);
        }

        public override void Render(IRenderContext rc)
        {
            //int on = OnCount;
            //if (on == 0)
            //    return;
            if (initialized == false)
            {
                var x1 = XAxis.Transform(X); //坐标转换成位置，放置点在初始坐标
                var y1 = YAxis.Transform(Y);
                Position = new ScreenPoint(x1, y1);

                Bounds = new OxyRect(new ScreenPoint(x1 - 10, y1 - 10), new OxySize(20, 20));
                rc.DrawCircle(new ScreenPoint(x1, y1), 10, OxyColor.FromAColor(128, OxyColors.LightSteelBlue), OxyColors.Black, 1, EdgeRenderingMode.Automatic);
                rc.DrawText(new ScreenPoint(x1, y1), this.Label, OxyColors.Black, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);

                initialized = true;
                return;
            }


            //var subHeight = rc.MeasureText("0123456789").Height + 2;
            var subHeight = rc.MeasureText("01").Height + 2;
            var subWidth = Width / 3;

            var height = subHeight;  //var height = subHeight * (on + 1);

            //var x = Position.X + (Sign(HorizontalAlignment) + 1) * Width / 2;
            var x = Position.X;
            var y = Position.Y + (Sign(VerticalAlignment) + 1) * height / 2;
            var topLeft = new ScreenPoint(x - 10, y - 10);
            //Bounds = new OxyRect(topLeft, new OxySize(Width, height));
            Bounds = new OxyRect(topLeft, new OxySize(20, 20));


            rc.DrawCircle(new ScreenPoint(x, y), 10, OxyColor.FromAColor(128, OxyColors.LightSteelBlue), OxyColors.Black, 1, EdgeRenderingMode.Automatic);

            //rc.DrawText(new ScreenPoint(x + subWidth * 0.5, y + subHeight * 0.5), "1", OxyColors.Black, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);
            rc.DrawText(new ScreenPoint(x, y), this.Label, OxyColors.Black, horizontalAlignment: HorizontalAlignment.Center, verticalAlignment: VerticalAlignment.Middle);
        }

        public double TranslateScreenPoint(ScreenPoint sp)
        {
            if (XAxis.IsVertical())
                sp = new ScreenPoint(sp.Y, sp.X);

            var newPosition = XAxis.InverseTransform(sp.X, sp.Y, YAxis).X;
            if (XAxis.ActualMinimum > newPosition || XAxis.ActualMaximum < newPosition)
                newPosition = double.NaN;
            return newPosition;
        }

        public double TranslateScreenPoint2(ScreenPoint sp)
        {
            if (YAxis.IsHorizontal())
                sp = new ScreenPoint(sp.Y, sp.X);

            var newPosition = YAxis.InverseTransform(sp.X, sp.Y, YAxis).Y;
            if (YAxis.ActualMinimum > newPosition || YAxis.ActualMaximum < newPosition)
                newPosition = double.NaN;
            return newPosition;
        }

        public ScreenPoint TranslateScreenPoint3(ScreenPoint sp)
        {
            if (XAxis.IsVertical())
                sp = new ScreenPoint(sp.Y, sp.X);

            var X = XAxis.InverseTransform(sp.X, sp.Y, XAxis).X; //位置转换坐标
            var Y = YAxis.InverseTransform(sp.X, sp.Y, YAxis).Y;
            //if (XAxis.ActualMinimum > X || XAxis.ActualMaximum < X)
            //    X = double.NaN;

            //if (YAxis.ActualMinimum > Y || YAxis.ActualMaximum < Y)
            //    Y = double.NaN;


            return new ScreenPoint(X, Y);
        }

        protected override HitTestResult HitTestOverride(HitTestArguments args)
        {
            if (Bounds.Contains(args.Point))
            {
                return new HitTestResult(this, args.Point);
            }
            return null;
        }

        private bool moused = false;
        private ScreenVector mouseOffset;

        private void CursorInfoAnnotation_MouseMove(object sender, OxyMouseEventArgs e)
        {
            //System.Windows.MessageBox.Show("xMin:" + XAxis.ActualMinimum + " xMax:" + XAxis.ActualMaximum + " yMin" + YAxis.ActualMinimum + " yMax:" + YAxis.ActualMaximum);
            var sp = e.Position;
            var X = XAxis.InverseTransform(sp.X, sp.Y, XAxis).X; //位置转换坐标
            var Y = YAxis.InverseTransform(sp.X, sp.Y, YAxis).Y;

            if (XAxis.ActualMinimum > X)
            {
                X = XAxis.ActualMinimum;
            }

            if (XAxis.ActualMaximum < X)
            {
                X = XAxis.ActualMaximum;
            }

            if (YAxis.ActualMinimum > Y)
            {
                Y = YAxis.ActualMinimum;
            }
            if (YAxis.ActualMaximum < Y)
            {
                Y = YAxis.ActualMaximum;
            }

            e.Position = new ScreenPoint(XAxis.Transform(X), YAxis.Transform(Y)); //坐标转换位置,防止将点拖出坐标系

            if (moused && e.Position.X >= 0 && e.Position.Y >= 0 && e.Position.X < PlotModel.Width && e.Position.Y < PlotModel.Height)
            {
                Position = e.Position - mouseOffset;
                PlotModel.InvalidatePlot(false);
            }
        }

        private void CursorInfoAnnotation_MouseUp(object sender, OxyMouseEventArgs e)
        {
            moused = false;
        }

        private void CursorInfoAnnotation_MouseDown(object sender, OxyMouseDownEventArgs e)
        {
            if (e.ChangedButton == OxyMouseButton.Left)
            {
                moused = true;
                mouseOffset = e.Position - Position;
                e.Handled = true;
            }
        }

        private int Sign(HorizontalAlignment horizontalAlignment)
        {
            switch (horizontalAlignment)
            {
                case HorizontalAlignment.Left:
                    return -1;
                case HorizontalAlignment.Center:
                    return 0;
                case HorizontalAlignment.Right:
                    return +1;
                default:
                    throw new ArgumentException(nameof(horizontalAlignment));
            }
        }

        private int Sign(VerticalAlignment verticalAlignment)
        {
            switch (verticalAlignment)
            {
                case VerticalAlignment.Top:
                    return -1;
                case VerticalAlignment.Middle:
                    return 0;
                case VerticalAlignment.Bottom:
                    return +1;
                default:
                    throw new ArgumentException(nameof(verticalAlignment));
            }
        }
    }



    public class CursorAnnotation : Annotation
    {
        public double Position { get; set; } = double.NaN;
        public OxyColor Color { get; set; } = OxyColors.LightGray;
        public bool ReverseX { get; set; } = false;
        public bool ReverseY { get; set; } = false;

        public double BoxSize { get; set; } = 18;
        public double LineThickness { get; set; } = 1;

        public bool IsEnabled { get; set; } = true;

        public CursorAnnotation(string xAxisKey, string yAxisKey)
        {
            XAxisKey = xAxisKey;
            YAxisKey = yAxisKey;
            Layer = AnnotationLayer.BelowAxes;

            this.MouseDown += CursorAnnotation_MouseDown;
            this.MouseUp += CursorAnnotation_MouseUp;
            this.MouseMove += CursorAnnotation_MouseMove;
        }

        public bool IsOn => IsEnabled && XAxis.IsAxisVisible && !double.IsNaN(Position);

        public void GetPoints(out ScreenPoint near, out ScreenPoint far, out ScreenPoint off)
        {
            var p = Position;
            if (double.IsNaN(p))
                p = ReverseX ? XAxis.ActualMaximum : XAxis.ActualMinimum;

            if (this.YAxisKey == null)
            {
                var xp = XAxis.Transform(p);
                near = new ScreenPoint(xp, XAxis.IsHorizontal() ? XAxis.PlotModel.PlotArea.Bottom : XAxis.PlotModel.PlotArea.Left);
                far = new ScreenPoint(xp, XAxis.IsHorizontal() ? XAxis.PlotModel.PlotArea.Top : XAxis.PlotModel.PlotArea.Right);
            }
            else
            {
                near = XAxis.Transform(p, YAxis.ActualMinimum, YAxis);
                far = XAxis.Transform(p, YAxis.ActualMaximum, YAxis);
            }

            if (ReverseY)
            {
                var t = near;
                near = far;
                far = t;
            }

            if (XAxis.IsVertical())
            {
                near = new ScreenPoint(near.Y, near.X);
                far = new ScreenPoint(far.Y, far.X);
                off = new ScreenPoint(near.X + (ReverseY ? BoxSize / 2 : -BoxSize / 2), far.Y);
            }
            else
            {
                off = new ScreenPoint(near.X, far.Y + (ReverseY ? BoxSize / 2 : -BoxSize / 2));
            }
        }

        public double TranslateScreenPoint(ScreenPoint sp)
        {
            if (XAxis.IsVertical())
                sp = new ScreenPoint(sp.Y, sp.X);

            var newPosition = XAxis.InverseTransform(sp.X, sp.Y, YAxis).X;
            if (XAxis.ActualMinimum > newPosition || XAxis.ActualMaximum < newPosition)
                newPosition = double.NaN;
            return newPosition;
        }

        public override void Render(IRenderContext rc)
        {
            if (!IsEnabled || !XAxis.IsAxisVisible || XAxis.ActualMinimum > Position || XAxis.ActualMaximum < Position)
                return;

            GetPoints(out ScreenPoint near, out ScreenPoint far, out ScreenPoint off);

            rc.DrawLine(new[] { near, far }, Color, LineThickness, EdgeRenderingMode.Automatic);

            //var offRect = new OxyRect(off.X - BoxSize / 2, off.Y - BoxSize / 2, BoxSize, BoxSize);
            var offRect = new OxyRect(100, 100, BoxSize, BoxSize);
            //rc.DrawRectangle(offRect, Color, OxyColors.Transparent, 0, EdgeRenderingMode.Automatic);
            rc.DrawRectangle(offRect, Color, OxyColors.Yellow, 2, EdgeRenderingMode.Automatic);
        }

        protected override HitTestResult HitTestOverride(HitTestArguments args)
        {
            if (!IsEnabled || !XAxis.IsAxisVisible || XAxis.ActualMinimum > Position || XAxis.ActualMaximum < Position)
                return null;

            GetPoints(out ScreenPoint near, out ScreenPoint far, out ScreenPoint off);

            var lineHitRect = new OxyRect(near, far).Inflate(new OxyThickness(LineThickness + 1));
            var offRect = new OxyRect(off.X - BoxSize / 2, off.Y - BoxSize / 2, BoxSize, BoxSize);

            if (lineHitRect.Contains(args.Point) || offRect.Contains(args.Point))
            {
                return new HitTestResult(this, near);
            }
            return null;
        }

        private bool moused = false;

        private void CursorAnnotation_MouseMove(object sender, OxyMouseEventArgs e)
        {
            if (moused)
            {
                Position = TranslateScreenPoint(e.Position);
                PlotModel.InvalidatePlot(false);
            }
        }

        private void CursorAnnotation_MouseUp(object sender, OxyMouseEventArgs e)
        {
            moused = false;
        }

        private void CursorAnnotation_MouseDown(object sender, OxyMouseDownEventArgs e)
        {
            if (e.ChangedButton == OxyMouseButton.Left)
            {
                moused = true;
                e.Handled = true;
            }
        }
    }
}

**Comment by VisualMelon** [comment] 2022-05-26 14:56
The `if (initialized == false)` bit in `Render` is weird: you should be computing the position from the X/Y data-space coordinates, rather than using the computed screen-space coordinates (it's not expensive, so no harm doing it whenever you need to know the screen coordinates).

**Comment by yanglei629** [comment] 2022-05-26 15:11
Hi,this part is for putting the point in initial corrdinate.i create a annotation with a initial coordinate such as（50，0 by setting X/Y，so i should translate it to screenpoint firstly,it work as my expect.But this is not correspond with the scale problem.I need to translate the coordinate to screenpoint every time when the window scale.

**Comment by yanglei629** [comment] 2022-05-27 07:51
Hi,I hava solved the problem with check PlotModel width and height.

##Snapshot
![image](https://user-images.githubusercontent.com/81857996/170655524-262f8e96-e214-4b4f-aaca-3ac9d7a6efd9.png)

**Comment by VisualMelon** [comment] 2023-05-14 14:46
Closing as looks like the issue is solved: feel free to reopen if this is not the case.

**Closed as completed by VisualMelon** 2023-05-14 14:46 UTC
