### ISSUE TITLE
Annotations YAxisKey

### ISSUE THREAD

**Issue by jonathantwite** [oxyplot/oxyplot#743] opened 2016-01-20 09:49 UTC
When plotting multiple data series and defining multiple axis, it would be preferable to be able to assign which axis an annotation is linked with, as you can with the series.
(Working with WPF)

**Comment by objorke** [comment] 2016-01-20 18:28
Isn't the `YAxisKey` property working? 
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Annotations/Annotation.cs#L56
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Annotations/Annotation.cs#L64

**Comment by jonathantwite** [comment] 2016-01-21 08:34
What's wrong then? YAxisKey is not available?

I installed OxyPlot for WPF from NuGet (version: 1.0.0-unstable1966 (Prerelease)) and so also have OxyPlot core library (PCL) of the same version

<Window x:Class="HealthChart.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:oxy="http://oxyplot.org/wpf"
        xmlns:ann="clr-namespace:OxyPlot.Annotations;assembly=OxyPlot"
        xmlns:converters="clr-namespace:HealthChart.Converters"
        xmlns:diag="clr-namespace:System.Diagnostics;assembly=WindowsBase"
        xmlns:ignore="http://www.galasoft.ch/ignore"
        mc:Ignorable="d ignore"
        MinHeight="300"
        MinWidth="300"
        SizeToContent="WidthAndHeight"
        Title="Health Chart"
        DataContext="{Binding Main, Source={StaticResource Locator}}">


    <oxy:Plot Height="400" Width="600">
        <oxy:Plot.Axes>
            <oxy:DateTimeAxis StringFormat="dd MMM yyyy" x:Name="XAxis" Title="Date" />
            <oxy:LinearAxis Key="User1Axis" Position="Left" Minimum="{Binding User1GraphMin}" Maximum="{Binding User1GraphMax}" Title="{Binding User1Name}" />
            <oxy:LinearAxis Key="User2Axis" Position="Right" Minimum="{Binding User2GraphMin}" Maximum="{Binding User2GraphMax}" Title="{Binding User2Name}" /> 
        </oxy:Plot.Axes>
                    
        <oxy:Plot.Annotations>
            <oxy:RectangleAnnotation MinimumY="{Binding User1NormalMin}" MaximumY="{Binding User1NormalMax}" Text="Normal" Layer="BelowSeries" Fill="Green" />
            <oxy:RectangleAnnotation MinimumY="{Binding User1OverMin}" MaximumY="{Binding User1OverMax}" Text="Overweight" Layer="BelowSeries" />
        </oxy:Plot.Annotations>
                    
        <oxy:Plot.Series>
            <oxy:LineSeries ItemsSource="{Binding User1Data}" DataFieldX="Date" DataFieldY="{Binding GraphToShow}" YAxisKey="User1Axis" Title="{Binding User1Name}" />
            <oxy:LineSeries ItemsSource="{Binding User2Data}" DataFieldX="Date" DataFieldY="{Binding GraphToShow}" YAxisKey="User2Axis" Title="{Binding User2Name}" />
        </oxy:Plot.Series>
    </oxy:Plot>

**Comment by objorke** [comment] 2016-01-21 21:17
OK, I see. The properties were missing in the Wpf `Annotation` wrapper

**Comment by objorke** [comment] 2016-01-21 21:18
I have created a PR

**Comment by objorke** [comment] 2016-01-21 21:36
Please try the latest pre-release build and close this issue if the problem is solved.

**Closed** 2016-02-01 13:14 UTC
Labels: annotations, confirmed-bug, easy-fix, please-verify, WPF
