### ISSUE TITLE
Axis disappears In zoom-in oxyplot wpf 

### ISSUE THREAD

**Issue by aliridha1510** [oxyplot/oxyplot#1441] opened 2019-12-05 14:52 UTC
Hi there

I am using Oxyplot in my C# application.

in this diagram, does the axis disappear when I zoom in on the diagram?

**Diagram with zoom-out**

![axisdefault](https://user-images.githubusercontent.com/23260197/70244824-6c12b800-1775-11ea-84c1-7fcad57ad630.PNG)

**Diagram  zoom-in**
![Axis2](https://user-images.githubusercontent.com/23260197/70244876-7fbe1e80-1775-11ea-88e4-3121a98d3202.PNG)

I have tried to set the Shift property for all my axes, but it has no effect.

Any ideas? Thank you in advance!

Platform:
.NET version:
WPF
Oxyplot.wpf Version 1.0.0

Example Code  : 

 

   public void TestModel()
        {
 
            XAxis = new LinearAxis
            {
                Key = "xAxisKeyPositive",
                Position = AxisPosition.Top,
                PositionTier = 0,
                AxislineStyle = LineStyle.Solid,
                Minimum = 0,
                StartPosition = 0.5,
                EndPosition = 1,
                PositionAtZeroCrossing = true,
                AbsoluteMinimum = 0,
                Title ="X1",

            };
            Model.Axes.Add(XAxis);

            XAxis2 = new LinearAxis
            {
                Key = "xAxisKeyNegative",
                Position = AxisPosition.Top,
                PositionTier = 0,
                AxislineStyle = LineStyle.Solid,
                Minimum = 0,
                AxislineColor = OxyColors.Gold,
                StartPosition = 0.5,
                EndPosition = 0,
                PositionAtZeroCrossing = true,
                IsAxisVisible = true,
                AbsoluteMinimum = 0,
                Title = "X",

            };
            Model.Axes.Add(XAxis2);
            YAxis = new LinearAxis
            {
                Key = "yAxisKeyPositive",
                Position = AxisPosition.Left,
                AxislineStyle = LineStyle.Solid,
                Minimum = 0,
                AxislineColor = OxyColors.Green,
                PositionTier = 0,
                StartPosition = 0.5,
                EndPosition = 1,
                PositionAtZeroCrossing = true,
                AbsoluteMinimum = 0,
                AbsoluteMaximum = 1000,
                Title = "Y",

            };
            Model.Axes.Add(YAxis);
            YAxis2 = new LinearAxis
            {
                Key = _yAxisKeyNegative,
                Position = AxisPosition.Right,
                AxislineStyle = LineStyle.Solid,
                Minimum = 0,
                AxislineColor = OxyColors.Violet,
                PositionTier = 0,
                StartPosition = 0.5,
                EndPosition = 0,
                PositionAtZeroCrossing = true,
                AbsoluteMinimum = 0,
             
            };
            Model.Axes.Add(YAxis2);

        
            Model.PlotAreaBorderThickness = new OxyThickness(1, 1, 1, 1);
          
	
	}

**Comment by Jonarw** [comment] 2019-12-09 07:21
Could you provide a code sample which reproduces the issue? Thanks!

**Comment by aliridha1510** [comment] 2019-12-09 13:50
@Jonarw   
these bugs occur when you add different axes in the same model, and then 
**PlotAreaBorderThickness as new OxyThickness(1, 1, 1, 1 );**
declared.
but if you declare **PlotAreaBorderThickness as new OxyThickness(0, 0, 0, 0);**
does not happen, but the diagram will not have an AreaBorder.

bug exists in both versions of Nuget 

Thanks

**Comment by VisualMelon** [comment] 2019-12-09 15:45
Reproduced in WinForms also.

With the above example, the horizontal axis lines disappear when the top (T) axis is panned away from zero (which occurs when zooming), and the vertical axis lines disappear when the left (X1) axis is panned away from zero. The other two axes seem to produce no such effect.

**Comment by aliridha1510** [comment] 2019-12-09 16:54
@VisualMelon  Thanks for your quick answer, you can explain to me how to disable both. ?

**Comment by VisualMelon** [comment] 2019-12-09 17:06
You can comment out both instances of `drawAxisLine = false`, but that's not a proper solution. I've not got my head around what is going on, but I hoped that might help someone else with more time. I suspect the code was written without consideration to the possibility of having a zero-centered axis which doesn't extend the whole plot bounds, or indeed the possibility of having 2 such axes. I have very little experience with zero-crossing axes, and I've really no idea at the moment how this could be properly resolved.

It might make sense to compare the `axisPosition` to the actual plot bounds rather than assuming the data min/max are representative, but I've not tested this.

You might consider adding the example to the Issues examples in the ExampleLibrary, and making a pull-request: that will make it easier for other people to test.

**Comment by VisualMelon** [comment] 2019-12-09 17:24
Here is a gist with a quick change to those checks that I've thrown together which seems to preserve the existing behaviour while resolving this particular issue: https://gist.github.com/VisualMelon/df69be6aacb6c9b9187e45fbc084321c

**Comment by aliridha1510** [comment] 2019-12-09 17:47
this is here small example project with the above example : https://github.com/aliridha1510/OxyplotExample.git

**Comment by VisualMelon** [comment] 2020-02-08 23:04
Upon further testing, the fix I proposed doesn't work, because as soon as you pan the axes beyond the plot bounds they still disappear.

**Comment by VisualMelon** [comment] 2020-02-09 10:40
What appears to be a working (though a tad unpleasant) solution appears in 
f35b7fd. The change is to only clip the axis line when the perpendicular axis places the axis line outside the plot bounds. In practise, it has a fuzzy check near the border because the `ActualMinimum` and `ActualMaximum` of the perpendicular axis are often a tiny amount out.

It adds another example also, to demonstrate the behaviour of a 'normal' pair of zero-crossing axes when moved near the border.

**Closed** 2020-08-04 15:45 UTC
Labels: axes, bug

**Comment by swethakini-ofc** [comment] 2020-08-15 10:48
@VisualMelon On the similar lines even border of histogram seems to disappear on zoom. All four bars shown below do not have similar border thickness at the top
![image](https://user-images.githubusercontent.com/60653002/90310774-64193380-df12-11ea-8161-89793dd78b62.png)

I hope following also would be fixed with your fix
![image](https://user-images.githubusercontent.com/60653002/90310837-e4d82f80-df12-11ea-9523-967191190927.png)

**Comment by VisualMelon** [comment] 2020-08-15 10:51
@swethakini-ofc that looks like a completely different issue with a different cause. Which platform are you using, and which version?

**Comment by swethakini-ofc** [comment] 2020-08-17 10:53
@VisualMelon I am using oxyplot 2.0 , Net 4.6.1 C# WPF on windows 10

**Comment by VisualMelon** [comment] 2020-08-17 11:19
@swethakini-ofc I can't reproduce anything like this. Can you open a new issue with some example code, and any information about scaling etc. that might be going on in your application.

**Comment by swethakini-ofc** [comment] 2020-08-20 10:29
@VisualMelon  I have created new issue and submitted code in [https://github.com/oxyplot/oxyplot/issues/1647](url). This issue is mainly with scaling

**Comment by swethakini-ofc** [comment] 2020-08-20 10:32
@VisualMelon I have created new issue in [https://github.com/oxyplot/oxyplot/issues/1647](url) this issue is mainly because of scaling
