### ISSUE TITLE
There should be a minimum of 2 labels per axis

### ISSUE THREAD

**Issue by Trass3r** [oxyplot/oxyplot#749] opened 2016-01-26 14:34 UTC
As you can see below MajorStep is auto-calculated in a way that may result in 1 or even 0 labels on the y-axis (The 3rd plot sometimes shows the 0, sometimes not depending on the random data):
![image](https://cloud.githubusercontent.com/assets/404623/12583196/ceb7b8e2-c441-11e5-88a5-645874c88bee.png)

**Comment by tibel** [comment] 2016-01-26 15:49
Seems to be a duplicate of #24

**Closed** 2016-01-26 16:31 UTC
