### ISSUE TITLE
HeatMap throws an exception if the data is 1xN or Nx1

### ISSUE THREAD

**Issue by cjstephen** [oxyplot/oxyplot#1031] opened 2016-12-08 13:38 UTC
### Steps to reproduce
Create a PlotView with WPF/XAML in an MVVM application e.g.
 <oxy:PlotView Model="{Binding ImageModel}" MinWidth="20" MinHeight="20" HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>

If the PlotModel supplied has data that is an Array2D of 1xN or Nx1 then an exception is thrown and displayed instead of the plot (attached screengrab). Something in the rendering is attempting to divide by zero it seems. I've done this with the Cartesian plot type.

OxyPlot 1.0
Platform: Windows 10
.NET version: 4.0
FSharp: 4.4.0

### Expected behaviour

Same scale for X & Y axes. Plot should be sized to fit the longer direction in the parent. The context is that images are being built as heatmaps with some resolution and aspect ratio. Sometimes it's useful to make a one dimensional image scanning in one direction only, which makes a 1xN heatmap useful as a specialisation of the general MxN. Displaying 2xN is fine.

### Actual behaviour

![1xnbug](https://cloud.githubusercontent.com/assets/8471933/21011771/b775c748-bd4a-11e6-9a69-a64900de3144.png)

**Comment by objorke** [comment] 2016-12-08 21:46
Is this a duplicate of #129?

**Comment by cjstephen** [comment] 2016-12-09 12:22
Yes, sorry. I somehow missed that when I searched before

**Closed** 2016-12-09 23:08 UTC
Labels: duplicate, series, unconfirmed-bug
