### ISSUE TITLE
Support of several X-coordinates for same Y-coordinate

### ISSUE THREAD

**Issue by abrasat** [oxyplot/oxyplot#1629] opened 2020-07-22 08:41 UTC
### Feature description

I have an application where each line-series contains points that are looking like this: (Xn_1, Xn_2, Yn).
Practically for each Y value there are 2 corresponding X-values: one of them is for instance some absolute X-value (could be a DateTime time-stamp) and the second X  value is for instance a relatively calculated  value (like a percentage from something).  I would then add 2 linear axes to the plot, one for the each of the 2 defined X values.
Could the DataPoint class be extended to take several X coordinates for one Y coordinate?

**Comment by VisualMelon** [comment] 2020-07-22 08:47
Realistically, I think not. There have been a couple of other issues lately discussing having multiple sets of labels per axis (#1357, #1336), and perhaps this would be worth thinking about.

To some extent, these could addressed by having multiple axes on different tiers all slaved together.

**Comment by abrasat** [comment] 2020-07-22 09:06
For the application I am thinking about, I have actually a plot representing the values of different process data between 2 events (like start and end of production process). The 2 events represent the 0 - 100 % scale which is used for the X axis.
I would need the option to add a second X axis to represent the absolute time-stamps for the data points between the 2 events (an option would be to toggle between the 2 X axes, or, maybe even better, to be able to add/remove the DateTime X axis whenever the user activates it, by context menu or whatever)..
Right now I show the DateTime values for each DataPoint in a customized TrackerFormatString, but having an optional additional DateTime axis would be much more user-friendly)

**Comment by abrasat** [comment] 2020-07-22 10:11
Is there any possiblity to stack two X axes at the bottom, one above the other?

**Comment by VisualMelon** [comment] 2020-07-22 10:34
Yes, the `Axis.PositionTier` property allows you to stack axes on the same size of the plot (there is big example in example library under Axis Examples).

**Comment by abrasat** [comment] 2020-07-22 10:37
Ok, thanks, I will take a look.
Is it possible to run the examples from the example library ?

**Comment by abrasat** [comment] 2020-07-22 11:17
Unfortunately I dont see the second axis as in the example browser. The scale of the second linear axis is dsplayed, but the values below the scale and the title are missing. Looks that these are cut off from the plot view. I tried to set the Margin property of the PlotView, but it did not help. Any idea what happens?

**Comment by VisualMelon** [comment] 2020-07-22 11:28
That does sound like an issue with the margins: can you provide a screen shot or reproducing code?

If you set the margins to `NaN`, do they appear? Axes exist within the plot the margins, so if they are set manually, then they need to accommodate all the axes.

**Comment by abrasat** [comment] 2020-07-22 11:48
Actual code + screenshot.
Is it necessary to calculate minimum and maximum  for the second axis? But why is not even the title displayed? 

![position_tier_x_axes](https://user-images.githubusercontent.com/6650450/88172743-c0de4280-cc21-11ea-9a28-16e31382ef60.png)


```
myPlotModel.Axes.Add(new LinearAxis { Position = AxisPosition.Bottom, PositionTier = 0, Title = "Processing (%)" });
myPlotModel.Axes.Add(new LinearAxis { 
                    AxislineStyle = LineStyle.Solid,
                    Position = AxisPosition.Bottom,
                    PositionTier = 1,
                    Title = "Time"
                });
```

**Comment by VisualMelon** [comment] 2020-07-22 11:54
It will be necessary to compute them if you want it to say anything meaningful, but it should default to [0, 100] and display as such.

It does look exactly like it is being clipped. If you make the plot margin NaN or double whatever it is now, does that change anything at all?

**Comment by abrasat** [comment] 2020-07-22 12:40
I had this margin in xaml:

```
<Grid>
    <oxySkia:PlotView Model="{Binding Model.PlotModel}" Controller="{Binding Model.PlotController,UpdateSourceTrigger=PropertyChanged}" Background="White" Margin="30,30,30,30">

```

How can I set NaN as Margin?

**Comment by VisualMelon** [comment] 2020-07-22 12:50
The margin on the `PlotView` is just the margin defined for any control. You have to set it on `PlotModel`, where it should default to all `NaN`. Could the margins be being set elsewhere? This is often done to avoid the axes 'bouncing' because OxyPlot computes them based on what is displayed, and this can be undesirable upon user interaction.

**Comment by abrasat** [comment] 2020-07-22 13:04
You are right, thanks!
I had this:
```
var myPlotModel = new PlotModel
                {
                    Title = plotTitle,
                    PlotMargins = new OxyThickness(50, 0, 0, 40)
                };
```

After changing to this
```
var myPlotModel = new PlotModel
                {
                    Title = plotTitle,
                    PlotMargins = new OxyThickness(50, 0, 0, 80)
                };
```
, I see the second X axis

**Comment by abrasat** [comment] 2020-07-22 14:34
Is there any possibility to couple/synchronize the second DateTime X axis with the first X axis? For instance when zooming the plot and respectively the first X-axis, to also zoom/adapt the DateTime X axis. Does anyone have maybe a code sample about how to achieve such a functionality?

**Comment by VisualMelon** [comment] 2020-07-22 14:40
There is no built in support for slaving. It's been a while since I tried, but you should be able to hook on `OnAxisChanged` on both axes and update the other accordingly. This should work because it isn't called when you change the minimum/maximum directly, but it means that any manual update will have to be intercepted some other way.

The example library could do with an example of this...

**Comment by abrasat** [comment] 2020-07-22 14:50
I understand the theory, not sure about the practical implementation... 
To get the "Zoom effect" on the second axis I would have to calculate somehow the "zoom factor" on the first X-Axis in OnAxisChanged?
And then to zoom manually the second X axis, I would have to recalculate the minimum and maximum properties  for it?
Unfortunately there are no samples of handling OnAxisChanged or calling ZoomAt in the example library...

**Comment by VisualMelon** [comment] 2020-07-22 14:56
`OnAxisChanged` is called after the axis recomputes itself: the easiest way would be to compute new minimum/maximum values for the 'other' axis from the (new) minimum/maximum values of the changed axis. Take a look at #1320.

If you're not in a rush, I'll try to put together a small sample, though these events are due for removal. #59 shows an example of changing axis zooming behaviour by modifying the controller (the 'proper' way of doing things).

**Comment by abrasat** [comment] 2020-07-22 15:40
Thanks for the information!
Thank you also for the sample you are working on, there is no rush!

**Comment by VisualMelon** [comment] 2020-07-22 16:31
Just threw this together: not properly tested ;)

    [Example("Slaved axes")]
    public static PlotModel SlavedAxes()
    {
        var plotModel = new PlotModel() { Title = "Slaved Axes" };

        var y2axis = new LinearAxis() { Position = AxisPosition.Right, Key = "y2" };

        var yaxis = new LinearAxis() { Position = AxisPosition.Left, Key = "y" };
        var xaxis = new LinearAxis() { Position = AxisPosition.Bottom, Key = "x" };

        plotModel.Axes.Add(y2axis);

        // add the 'real' axes (those referenced by series) last, so that they determine the 'reset' state
        plotModel.Axes.Add(yaxis);
        plotModel.Axes.Add(xaxis);

        Slave(y2axis, yaxis, x => x * 100);
        Slave(yaxis, y2axis, x => x / 100);

        plotModel.Series.Add(new FunctionSeries(Math.Sin, 0.0, 10.0, 0.01, "Sine") { XAxisKey = "x", YAxisKey = "y" });

        return plotModel;
    }

    private static void Slave(Axis slave, Axis master, Func<double, double> transform)
    {
        bool set = false;
        master.AxisChanged += (s, e) =>
        {
            if (set)
                return;
            set = true;
            slave.Zoom(transform(master.ActualMinimum), transform(master.ActualMaximum));
            set = false;
        };
    }

**Comment by abrasat** [comment] 2020-07-23 07:31
Thank you very much for the code sample!

One question: why did you call the Slave() method in both directions (yaxis to y2axis and y2axis to yaxis) ?

The zoom of the second slave axis basically works, but I am struggling to calculate the correct scaling factor for the transformation between the 2 axes, The problem is that the first axis ia a LinearAxis and the second one a DateTimeAxis.

And one more question: how can I show also the date, not only the time for the DateTimeAxis (or at least for one of the labels, otherwise it would be probably too full) ?

![scale_perc_ts](https://user-images.githubusercontent.com/6650450/88261736-26d0d580-ccc7-11ea-9387-f848db8912f2.png)

**Comment by VisualMelon** [comment] 2020-07-23 07:48
The `Slave` method is meant to 'slave' one axis to another: i.e. when the master axis changes, the slave axis will reflect this change. Calling it both ways means that an update on either axis will be updated. The boolean is to ensure it doesn't go into an infinite loop (i.e. catch the case where an update invokes an update; only makes sense if everything is consistent). You could just as well have a method that does the job of tying them together called `Mirror` or something; this is just the nomenclature and methodology I'm used to.

Regarding the date, I don't think that will be easy using built in functionality. What is really need is an axis where the ticks and labels denote ranges, not points. That axis could then be slaved to the others, and we'd start to approach the system described in #1357. It shouldn't be too hard to get something going by just overriding `GetTickValues`... I'll give it a go.

**Comment by VisualMelon** [comment] 2020-07-23 08:15
It's less than perfect... but hopefully it helps:

        public class DateRangeAxis : LinearAxis
        {
            public override void GetTickValues(
    out IList<double> majorLabelValues, out IList<double> majorTickValues, out IList<double> minorTickValues)
            {
                base.GetTickValues(out majorLabelValues, out majorTickValues, out minorTickValues);

                minorTickValues.Clear();

                if (majorLabelValues.Count == 0)
                {
                    majorLabelValues = new List<double>();

                    majorLabelValues.Add((ActualMinimum + ActualMaximum) / 2);
                }
                else
                {
                    majorLabelValues = new List<double>(majorTickValues);

                    for (int i = 0; i < majorLabelValues.Count; i++)
                    {
                        majorLabelValues[i] = majorTickValues[i] - ActualMajorStep / 2;
                    }

                    majorLabelValues.Add(majorTickValues[majorTickValues.Count - 1] + ActualMajorStep / 2);
                }
            }
        }

        [Example("DateRangeAxis")]
        public static PlotModel CustomDateRangeAxis()
        {
            var model = new PlotModel();
            
            model.Axes.Add(new DateRangeAxis
            {
                Position = AxisPosition.Bottom,
                Minimum = DateTimeAxis.ToDouble(new DateTime(2020, 07, 23)),
                Maximum = DateTimeAxis.ToDouble(new DateTime(2020, 07, 30)),
                LabelFormatter = d => DateTimeAxis.ToDateTime(d).DayOfWeek.ToString(),
                MajorStep = 1, // days
            });

            model.Axes.Add(new LinearAxis
            {
                Position = AxisPosition.Left,
            });

            return model;
        }

It'll be an uphill battle making it better without a more advanced axis system.

**Comment by abrasat** [comment] 2020-07-23 10:04
Thanks again, I will check it.
How exactly works the Zoom() function for a DateTimeAxis?
Should the transformation factor between the LinearAxis representing the percent values and the DateTime axis be calculated based on the DateTime representation as a double (returned by the DateTimeAxis.ToDouble() function ; I dont know exactly what the function calculates) of the minimum and maximum DateTime values ?

**Comment by VisualMelon** [comment] 2020-07-23 10:19
Sorry, I'm not quite sure what you are asking.

The 2-parameter `Zoom` method overload on any axis takes the minimum and maximum values to be shown on the axis, e.g. the `Slave` method just takes a mapping between one scale and the other, and just maps the minimum on one axis to a new minimum on the other. E.g. if your start (0%) date is `s` and your end (100%) date is `e` (both converted to doubles with `DateTimeAxis.ToDouble`, then the mapping to percentage from date is `d => 100 * (d - s) / (e - s)` (or you can omit the `100` and set the format string to `P`). Going the other way, `p => p * (e - s) / 100 + s`.

**Comment by abrasat** [comment] 2020-07-23 10:56
Thanks. Yes, that is what is was looking for.

Using the DateRangeAxis above, this is all I get:

![scale_perc_dtrange](https://user-images.githubusercontent.com/6650450/88279154-e3389480-cce3-11ea-9c72-eef21e9eaf56.png)

**Comment by VisualMelon** [comment] 2020-07-23 11:08
Sorry, probably should have explained it better.

It's set up to only show days: if there is only one day, then it just shows the name in the middle. The idea was to use it in conjunction with another `DateTimeAxis` on the same scale (e.g. slaved with an identity mapping `d => d`), the other axis showing the time, this showing the date (that can be configured by changing the formatter and step, but that's going to become painful very quickly, as it starts to try to reproduce what `DateTimeAxis` already tried to do). If, however, you only need it show days and won't be zooming out too much, then it will probably do the job. You can remove the title on one of the date axes to keep it pretty.

**Comment by abrasat** [comment] 2020-07-23 12:18
Ok, I understand now. How could I display for instance something like "15.03.2014" instead of the day of the week?

And one more question about the helper functions DateTimeAxis.ToDouble(DateTime value) and DateTimeAxis.ToDateTimeValue(double value). If I write this code:

```
var dtNow = DateTime.Now;
var dtDouble = DateTimeAxis.ToDouble(dtNow);
var dtNowAgain = DateTimeAxis.ToDateTime(dtDouble);
```
, the dtNow variable has the Kind property set to DateTime.Local, but dtNowAgain has the Kind property set to DateTime.Utc (the other values are identical).
Could be eventually a bug.

**Comment by VisualMelon** [comment] 2020-07-23 12:24
Check out [String Formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings).

Regarding datetime local/UTC, the static methods have to pick one and run with it, so there isn't much that can be done there. This could be a problem for presentation, but that can always be overriden.

**Comment by abrasat** [comment] 2020-07-23 12:27
Ok, I will check it.
I think the Kind property is read-only, can be set only when constructing a DateTime.

**Comment by abrasat** [comment] 2020-07-23 13:29
Got it working!

![scale_perc_dtrange_date](https://user-images.githubusercontent.com/6650450/88290404-028ced00-ccf7-11ea-9184-aec3994f50c0.png)

Would be possible to have a legend containing all the additional (optional) X axes (could be there are some more to come)? And then to be able to click on each item from the legend to toggle the display (or not) of each additional X axis (similar with the legend for LineSeries)?

**Comment by VisualMelon** [comment] 2020-07-23 13:39
The default legends only render series. You _could_ override and extend them to do otherwise, but it would be a lot of work.

In terms of long-term improvements, an `ILegendItem` interface might be a good idea: there isn't always a one-one mapping between series and legend entries, and it could allow other things (e.g. annotations) to join in. If you have ideas that would influence such a design, do make an issue about them so we can keep track of them.

**Comment by VisualMelon** [comment] 2020-07-23 13:40
The issue with the date disappearing presumably coincides with a tick appearing: at the point it stops rendering just one label and tries to render many, but they are probably 'off-screen'. It might make sense to detect if there is only one and re-center it.

**Comment by abrasat** [comment] 2020-07-23 14:04
Ok, thanks.
P.S. Not sure what happened, my last posting disappeared.

**Comment by abrasat** [comment] 2020-07-24 05:51
Is there any setting that allows displaying the title of a X Axis directly on the right (or left) side of the axis line, instead of below it?
Can the font size of the label texts for the axis be configured?

**Comment by VisualMelon** [comment] 2020-07-24 06:12
Title position isn't configurable (it's an old issue (#22) with a lot of difficulties with regards to how different axes with offset-titles should interact which the layout system can't really handle at the moment).

Label size should be controlled by by `PlotElement.FontSize`.

**Comment by abrasat** [comment] 2020-07-24 06:36
The configuration of the title position would be a very useful feature in my opinion...
What about the font size of the axis title, can this also be configured?

**Comment by VisualMelon** [comment] 2020-07-24 06:40
What it needs is someone familiar with the library to invest in the design work. It could probably be done quite easily, but it would go wrong when you have lots of axes. Maybe I'll have a go at a prototype over the weekend...

Axis title is `Axis.TitleFontSize`, though I think there is a bug in 2.0 involving that.

**Comment by abrasat** [comment] 2020-07-24 07:57
Thanks, it seems to work for my application

**Closed** 2020-08-04 16:24 UTC

**Comment by abrasat** [comment] 2020-08-10 08:36
@VisualMelon :  Should be possible to zoom the X-axis in my scenario? By moving the mouse wheel only the y-axis is zoomed. Where exactly should I place the mouse cursor (as decribed [here](https://oxyplot.readthedocs.io/en/latest/controllers/) to get the zoom for the x axis working?

**Comment by VisualMelon** [comment] 2020-08-10 08:44
@abrasat Without looking at your code for the plot model and controller, I can't really help. An X axis should always zoom when the mouse is over the plot area. Check you don't have any invisible axes, or axes which are configurated as non-zoomable/pannable or have absolute bounds.

**Comment by abrasat** [comment] 2020-08-10 09:27
@VisualMelon  I used basically the code above in this issue, to synchronize the additional x-axes with the x axis that I initially had (the one with the percentage values).
The problem seems to be in this code, with the 2-way synchronization of the x-axes.
```
Slave(y2axis, yaxis, x => x * 100);
Slave(yaxis, y2axis, x => x / 100);
```
If I remove the second Slave() call and thus have only a "one-way" axis synchronization, the zoom and pan functions work normally, also with the additional x axes.
