### ISSUE TITLE
LogarithmicAxis glitches with multiple series containing small data (WinForms)

### ISSUE THREAD

**Issue by t9mike** [oxyplot/oxyplot#589] opened 2015-09-18 02:28 UTC
If I have a dataset like:

            var x = new double[] { 1e5, 4e7 };
            var y1 = new double[] { 1e-14, 1e-12 };
            var y2 = new double[] { 1e-17, 1e-15 };

The Y axis is not formatted as I would expect:

![plot](https://cloud.githubusercontent.com/assets/1008514/9950593/bdf9b842-5d81-11e5-8ed0-30f36f696468.png)

I should see Y axis decades for 1e-17, 1e-16, ..., 1e-12.

But with larger but similar data, no issues:

            var x = new double[] { 1e5, 4e7 };
            var y1 = new double[] { 1e14, 1e12 };
            var y2 = new double[] { 1e17, 1e15 };

![plot](https://cloud.githubusercontent.com/assets/1008514/9950696/c339d912-5d82-11e5-8865-2c95454facaf.png)

Well, both have some wierd UseSuperExponentialFormat formatting with the 10*10^x business.

This is the code:

        public static void Log_Issue()
        {
            var model = new PlotModel();

            var xaxis = new LogarithmicAxis
            {
                UseSuperExponentialFormat = true,
                Position = AxisPosition.Bottom,
                MajorGridlineStyle = LineStyle.Dot,
                PowerPadding = true,
            };
            model.Axes.Add(xaxis);

            var yaxis = new LogarithmicAxis
            {
                UseSuperExponentialFormat = true,
                Position = AxisPosition.Left,
                MajorGridlineStyle = LineStyle.Dot,
                PowerPadding = true,
            };
            model.Axes.Add(yaxis);

            var x = new double[] { 1e5, 4e7 };
            var y1 = new double[] { 1e-14, 1e-12 };
            var y2 = new double[] { 1e-17, 1e-15 };
            //var y1 = new double[] { 1e14, 1e12 };
            //var y2 = new double[] { 1e17, 1e15 };

            var series1 = new LineSeries();
            series1.ItemsSource = Data_Points(x, y1);
            model.Series.Add(series1);

            var series2 = new LineSeries();
            series2.ItemsSource = Data_Points(x, y2);
            model.Series.Add(series2);

            using (var stream = File.Create("c:/temp/plot.png"))
            {
                var pngExporter = new PngExporter();
                pngExporter.Width = 450;
                pngExporter.Height = 200;
                pngExporter.Export(model, stream);
            }

        }

        private static IEnumerable<DataPoint> Data_Points(IList<double> x, IList<double> y)
        {
            for (int i = 0; i < x.Count; i++)
            {
                yield return new OxyPlot.DataPoint(x[i], y[i]);
            }
        }

**Comment by Isolocis** [comment] 2016-05-08 20:25
Hi,

While I was unable to reproduce the formatting problem on the Y-axis, I did manage to find the culprit for the 10*10^x values, which lies in the following code:
```C#
protected static readonly Func<double, double> Exponent = 
    x => Math.Floor(Math.Log(Math.Abs(x), 10));
```
The ` Math.Log ` function is less accurate for very small or very large numbers, although the deviation is still in the order of 1e-9. 

I can propose a fix for this problem, but unfortunately I can't help with the axis formatting issue.

**Closed** 2016-05-17 19:25 UTC
Labels: axes, confirmed-bug, help-wanted, high-priority, you-take-it
