### ISSUE TITLE
Plot does not appear on WindowsPhone and iOS (using Xamarin.Forms)

### ISSUE THREAD

**Issue by NicolaiSchmitt** [oxyplot/oxyplot#546] opened 2015-07-23 10:31 UTC
On windowsphone and iOS only the BackGroundColor of the PlotView is visible. The Plotmodel does not appear.
This was tested with:
Xamarin.Forms Version : 1.4.3.6374 & 1.4.3.6376
OxyPlot Version: 2015.1.889-alpha

On Android it works like it should

**Comment by staylr** [comment] 2015-08-10 08:32
I had to add a custom (empty) derived PlotView control and renderer as follows to make charts display when they were initially invisible on iOS. Not sure if this is the same problem.
Xamarin.Forms 1.5.0-pre1
OxyPlot Version: 2015.1.889-alpha


    [assembly:ExportRenderer(typeof(Oban.Mobile.Chart.ObanPlotView), typeof(Oban.Mobile.iOS.Renderer.ObanPlotViewRenderer))]

    namespace Oban.Mobile.iOS.Renderer
    {
        public class ObanPlotViewRenderer : OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer
        {
            protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
            {
                base.OnElementPropertyChanged(sender, e);

                this.Control.InvalidatePlot(false);
            }
        }
    }

**Comment by NicolaiSchmitt** [comment] 2015-08-11 09:03
On iOS that worked.
On wp the problem exists on.

**Comment by NicolaiSchmitt** [comment] 2015-08-11 12:30
Are there any ideas or workarounds for WindowsPhone?

**Comment by SkylarkA** [comment] 2015-09-14 15:13
I do have the same issue on Android!

Xamarin.Forms 1.5.0-pre1
OxyPlot Version: 2015.1.889-alpha

**Comment by luonganhtuanTMA** [comment] 2015-09-15 09:35
I have the same problem in iOS too.
I tried to custom the PlotView but it was not working.
Any way to work around this?

**Comment by dimitrijevic** [comment] 2015-10-01 15:01
Hi Nicolai,
How were you able to get it to show up on Android using 2015.1.889-alpha?
Are you using that NuGet package, I tried it but only background shows up.
Using latest Xamarin.Forms (PCL) w/ OP.Core 1046-alpha (OP.XF 899)...

P.S.
I force installed latest available prerelease OP.Core and OP.XF NuGet packages as they wouldn't install by itself because NuGet package manager was **unable to resolve dependencies. 'OxyPlot.Xamarin.Android 2015.1.999-alpha' is not compatible with 'OxyPlot.Xamarin.Forms 2015.1.889-alpha constraint: OxyPlot.Xamarin.Android (= 2015.1.889-alpha)'** or to install OP.XF itself because it was **unable to find a version of 'OxyPlot.Core' that is compatible with 'OxyPlot.Xamarin.Android 2015.1.889-alpha constraint: OxyPlot.Core (= 2015.1.889-alpha)'.**

**Comment by NicolaiSchmitt** [comment] 2015-10-05 07:37
Hi dimitrijevic,
on android it worked out of the box. I tried both, the nuget-package and the PCL/Project.
I had no problem on installing the nuget-package. You may try to rename the packages-folder in your project-folder and force visualstudio to redownload all packages (this may solve the resolving issues). 
In both cases (nuget and solution included project) i had the same issues.

Btw.: I also tried with xamarin version 1.4.4.6379-pre3 and 1.4.4.6392, and there is no difference.

Many greetings,
Nicolai Schmitt

**Comment by objorke** [comment] 2015-10-05 20:49
Please test with the latest OxyPlot.Xamarin packages - v1.0.0-unstable1849

**Comment by dimitrijevic** [comment] 2015-10-06 10:57
Excelent, shows up, Android at least...will try iOS/WP8 latter...Windows Phone uses just OxyPlot.Xamarin.Forms? Or will there be platform-specific package? Android tested on actual devices 4.1,4.2...

**Comment by objorke** [comment] 2015-10-07 20:00
The OxyPlot.Xamarin.Forms package depends on other packages, but these should be downloaded automatically. When you add OxyPlot.Xamarin.Forms to an iOS project, references to OxyPlot, OxyPlot.Xamarin.iOS, OxyPlot.Xamarin.Forms and OxyPlot.Xamarin.Forms.Platform.iOS should be added.

I just tested adding the packages in Visual Studio 2015, it seems to work for both Android, iOS and WP8. I will test from Xamarin Studio later. I will also try to reproduce the issue with a PlotView that is initially not visible. I could not reproduce the error for Android and WP8.

**Comment by anirbandebroy** [comment] 2015-10-08 04:53
I am currently using visual studio 2013 and oxyplot xamarin version 1.0.0-unstable1849.Android giving me desired result but i am not getting result on windows phone silverlight 8.1 and windows phone 8.1. i dont know what is the problem? i tried without xamarin form its working well in silverlight(windows phone silverligt 8.1)? Has anyone a solution for this xamarin form issue on windows phone?

**Comment by dimitrijevic** [comment] 2015-10-08 12:32
Tried it on 2015 too, using just OxyPlot.Xamarin.Forms version 1.0.0-unstable1849 (as for the OxyPlot dependent installed references those included: OxyPlot, OxyPlot.WP8 and OxyPlot.Xamarin.Forms.Platform.WP8), with the same background-only result (Windows Phone 8.0 Xamarin app on WP8.1 device and Xamarin.Forms version 1.5.0.6447) and using even simpler graph defined in App.cs of the Xamarin Portable PCL project like so:

public App()
        {
            // The root page of your application

            var plotModel = new PlotModel
            {
                Title = "OxyPlot in Xamarin.Forms",
                Subtitle = string.Format("OS: {0}, Idiom: {1}", Device.OS, Device.Idiom),
                Background = OxyColors.LightYellow,
                PlotAreaBackground = OxyColors.LightGray
            };
            var categoryAxis = new CategoryAxis { Position = AxisPosition.Bottom };
            var valueAxis = new LinearAxis { Position = AxisPosition.Left, MinimumPadding = 0 };
            plotModel.Axes.Add(categoryAxis);
            plotModel.Axes.Add(valueAxis);
            var series = new ColumnSeries();
            series.Items.Add(new ColumnItem { Value = 3 });
            series.Items.Add(new ColumnItem { Value = 14 });
            series.Items.Add(new ColumnItem { Value = 11 });
            series.Items.Add(new ColumnItem { Value = 12 });
            series.Items.Add(new ColumnItem { Value = 7 });
            plotModel.Series.Add(series);

            MainPage = new ContentPage
            {
                //    Content = new PlotView
                //    {
                //        Model = plotModel,
                //        VerticalOptions = LayoutOptions.Fill,
                //        HorizontalOptions = LayoutOptions.Fill,
                //    }
                Content = new StackLayout
                {
                    VerticalOptions = LayoutOptions.Center,
                    Children = {
                            Label1,
                            Label2,
                            Label3,
                            new PlotView
                            {
                                Model = plotModel,
                                BackgroundColor = Color.Aqua,
                                VerticalOptions = LayoutOptions.Fill,
                                HorizontalOptions = LayoutOptions.Fill,
                                HeightRequest = 300,
                                WidthRequest = 300
                            }
                        }
                }
            };
      }

*Could I be coding it wrong somehow?!*

**Comment by dimitrijevic** [comment] 2015-10-08 14:56
Ok, tried SampleDemo, here's my findings...it's not coding above...because it works there also.
But, there was a fail when I tried to add the NuGet, and the thing builds fine, but it wouldn't start after I added the NuGet to the PCL and WP8 projects.

The error is this one:
Additional information: Could not load file or assembly 'OxyPlot.Xamarin.Forms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

My guess is its some initial project setup difference for the Xamarin projects being created by default now and back when the SimpleDemo was created, but I couldn't find that difference in mine (I changed the culture to invariant manually and it still wouldn't show up in my project though that one would work - just not show graph).

**Comment by objorke** [comment] 2015-10-11 11:05
Please test v1.0.0-unstable.1857

I have changed the background color implementation for the Xamarin Forms and Xamarin native components. It looks correct in the demo apps, for both iOS, Android and WinPhone 8.0.
I also included the fix for the IsVisible bug in iOS.

Can we close this issue?

**Comment by anirbandebroy** [comment] 2015-10-12 09:33
Still the problem exist... it showing black screen...please check the code below for you reference...

            double minpoint = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(9));
            double maxpoint = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(18));
            double date = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(9));
            double date1 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(10));
            double date2 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(10.5));
            double date3 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(11));
            double date4 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(11.5));
            double date5 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(12));
            double date6 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(12.5));
            double date7 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(13));
            double date8 = DateTimeAxis.ToDouble(DateTime.Now.Date.AddHours(13.5));


            this.MyModel = new PlotModel { Title = "Queue History" };
            var dateTimeAxis1 = new DateTimeAxis();
            dateTimeAxis1.IsZoomEnabled = false;
            dateTimeAxis1.Minimum = date;
            dateTimeAxis1.Minimum = date4;
            MyModel.Axes.Add(dateTimeAxis1);
            var linearAxis1 = new LinearAxis();
            linearAxis1.IsZoomEnabled = false;
            MyModel.Axes.Add(linearAxis1);
            var lineSeries1 = new LineSeries();
            lineSeries1.Title = "Prediction";
            lineSeries1.BrokenLineThickness = 10;
            lineSeries1.LineStyle = LineStyle.Solid;
            lineSeries1.Points.Add(new DataPoint(date, 4));
            lineSeries1.Points.Add(new DataPoint(date1, 6));
            lineSeries1.Points.Add(new DataPoint(date2, 9));
            lineSeries1.Points.Add(new DataPoint(date3, 10));
            lineSeries1.Points.Add(new DataPoint(date4, 8));
            lineSeries1.Points.Add(new DataPoint(date5, 4));
            lineSeries1.Points.Add(new DataPoint(date6, 4));
            lineSeries1.Points.Add(new DataPoint(date7, 2));
            lineSeries1.Points.Add(new DataPoint(date8, 5));
            MyModel.Series.Add(lineSeries1);
            var pointAnnotation1 = new PointAnnotation();
            pointAnnotation1.X = date5;
            pointAnnotation1.Y = 4;
            pointAnnotation1.Fill = OxyColors.Blue;
            pointAnnotation1.Stroke = OxyColors.Blue;
            pointAnnotation1.StrokeThickness = 1;
            pointAnnotation1.Text = "Actual";
            MyModel.Annotations.Add(pointAnnotation1);

**Comment by anirbandebroy** [comment] 2015-10-12 09:43
I tried this default solution code in app.cs.. still the problem exist..its working fine in android but in windows silverlight it showing the black screen..

Oxyplotversion:v1.0.0-unstable.1857
Xamarin form Version:1.5.0.6447

 var plotModel = new PlotModel
                {
                    Title = "OxyPlot in Xamarin.Forms",
                    Subtitle = string.Format("OS: {0}, Idiom: {1}", Device.OS, Device.Idiom),
                    Background = OxyColors.LightYellow,
                    PlotAreaBackground = OxyColors.LightGray
                };
                var categoryAxis = new CategoryAxis { Position = AxisPosition.Bottom };
                var valueAxis = new LinearAxis { Position = AxisPosition.Left, MinimumPadding = 0 };
                plotModel.Axes.Add(categoryAxis);
                plotModel.Axes.Add(valueAxis);
                var series = new ColumnSeries();
                series.Items.Add(new ColumnItem { Value = 3 });
                series.Items.Add(new ColumnItem { Value = 14 });
                series.Items.Add(new ColumnItem { Value = 11 });
                series.Items.Add(new ColumnItem { Value = 12 });
                series.Items.Add(new ColumnItem { Value = 7 });
                plotModel.Series.Add(series);

                this.MainPage = new ContentPage
                {
                    Padding = new Thickness(0, 20, 0, 0),
                    Content = new PlotView
                    {
                        Model = plotModel,
                        VerticalOptions = LayoutOptions.Fill,
                        HorizontalOptions = LayoutOptions.Fill,
                    },
                };

**Comment by objorke** [comment] 2015-10-12 18:45
The SimpleDemo.WinPhone (Windows Phone 8.0) seems to work find on the emulator:

![image](https://cloud.githubusercontent.com/assets/439716/10435636/83aa5512-7121-11e5-9766-12a914f43864.png)

Did you include the following line in your WP8 application:
```csharp
OxyPlot.Xamarin.Forms.Platform.WP8.Forms.Init();
```

**Comment by objorke** [comment] 2015-10-12 18:48
@dimitrijevic: The renderer "initialization" is covered in: http://docs.oxyplot.org/en/latest/getting-started/hello-xamarin-forms.html. Maybe we can make it even more visible somewhere.
How are other Xamarin Forms custom components initialized?

**Comment by dimitrijevic** [comment] 2015-10-13 01:03
@objorke I had no problem with the visibility of instructions getting more exposure, it definitely should, though I admittedly didn't read getting started (so maybe other people might not read it too)...so maybe it's better for some exception to be thrown if OxyPlot is not initialized, because like me they might be unable to comprehend why was it working without initialization on Android, and just not show up on iOS or WP8 (though at the time I didn't know I was suppose to call Init)...1857 works fine for me on both Android and WP8, OxyPlot's great, thanks.

**Comment by anirbandebroy** [comment] 2015-10-14 05:43
@objorke IT SEEMS working fine for the above code but when I am doing like the below code

 <oxy:PlotView Model="{Binding MyModel}" VerticalOptions="Fill" HorizontalOptions="Fill" />

its seems working fine but if you changed the verticaloption and horizontaloption to center then its not working..

 <oxy:PlotView Model="{Binding MyModel}" VerticalOptions="Centre" HorizontalOptions="Centre" />

can you please tell me the reason? in some scenario may be i need to make vertical and horizontal option with different attribute like centre and start for those case oxyplot will not work? kindly tell me
if i wrong and coding wrong somehow?

**Comment by objorke** [comment] 2015-10-14 06:51
@anirbandebroy I guess this is related to width/height not being set.
I don´t think this is related to this background color issue, please stay on the topic here :-)

**Comment by anirbandebroy** [comment] 2015-10-14 06:56
@objorke its ok but its a oxyplot bug or my coding problem? earlier the topic was  Not working with Xamarin.Forms on WindowsPhone and iOS now its changed my bad :-)

**Comment by NicolaiSchmitt** [comment] 2015-10-14 09:47
Calling OxyPlot.Xamarin.Forms.Platform.WP8.Forms.Init() works well. 
Calling OxyPlot.Xamarin.Forms.Platform.iOS.Forms.Init() on IOS also works without the custom renderer.

should I close the issue ?

**Comment by objorke** [comment] 2015-10-17 10:21
@anirbandebroy Right, maybe I was to quick changing the title :-) I will change again.

**Comment by objorke** [comment] 2015-10-17 10:25
This seems to be fixed, closing issue.

**Closed by objorke** 2015-10-17 10:25 UTC
Labels: help-wanted, high-priority, iOS, please-verify, unconfirmed-bug, WP8, Xamarin.Forms
