### ISSUE TITLE
.net core 3 support 

### ISSUE THREAD

**Issue by JP75012** [oxyplot/oxyplot#1359] opened 2019-10-01 12:09 UTC
### Feature description

As .net framework will be stopped by the end of 2020, it is necessary to support.net core 3 since wpf can be executed on .net core 3

**Comment by VisualMelon** [comment] 2019-10-01 12:12
See https://github.com/oxyplot/oxyplot/issues/1331

Note that .NET Framework will not disappear over night: it will continue to be supported for a while yet. But yes, we should get on with this now that .NET Core 3 is actually out.

**Comment by JP75012** [comment] 2019-10-01 12:19
Yes of course . But new applications should be started on core 3 instead of framework to avoid a migration later.

**Comment by objorke** [comment] 2019-10-05 07:34
Agree we need to add support for .NET Core 3.0. This is a duplicate of #1331.

**Closed by objorke** 2019-10-05 07:34 UTC
Labels: duplicate
