### ISSUE TITLE
Xamarin Forms package not installing OxyPlot.Xamarin.Forms in shared project

### ISSUE THREAD

**Issue by kevinash** [oxyplot/oxyplot#412] opened 2015-03-16 14:40 UTC
I have a typical Xamarin Forms *shared* project and .Android and .iOS sub-projects. When I install a nugget package for OxyPlot Xamarin.Forms into either iOS or Android project (can't add packages to shared projects), nuget says OxyPlot.Xamarin.Forms  is successfully added, but in fact only *OxyPlot and OxyPlot.Xamarin.Forms.Platform.iOS* are in the project. But PlotView control is in OxyPlot.Xamarin.Forms which is not added:

`PM> Install-Package OxyPlot.Xamarin.Forms -Pre 
Attempting to resolve dependency 'OxyPlot.Core (= 2015.1.801-alpha)'.
Attempting to resolve dependency 'Xamarin.Forms (≥ 1.3.3.6323)'.
'OxyPlot.Xamarin.Forms 2015.1.801-alpha' already installed.
Adding 'OxyPlot.Core 2015.1.801-alpha' to MyApp.iOS.
Successfully added 'OxyPlot.Core 2015.1.801-alpha' to MyApp.iOS.
Adding 'OxyPlot.Xamarin.Forms 2015.1.801-alpha' to MyApp.iOS.
Successfully added 'OxyPlot.Xamarin.Forms 2015.1.801-alpha' to MyApp.iOS.`

Bottom line: after nugget install on MyApp.iOS I get:
OxyPlot
OxyPlot.Xamarin.Forms.Platform.iOS

and I need
OxyPlot
*OxyPlot.Xamarin.Forms*
OxyPlot.Xamarin.Forms.Platform.iOS

(same for Android). The problem with this is that I cannot reference PlotView from the cross-platform part of the code. 

*Second problem:* if I get the source and manually add OxyPlot.Xamarin.Forms.dll, the PlotView is blank in iOS, but it shows up in Android (same exact cross platform Xamarin Forms code):

XAML code (cross-platform):

`xmlns:oxy="clr-namespace:OxyPlot.Xamarin.Forms;assembly=OxyPlot.Xamarin.Forms"`

` <oxy:PlotView x:Name="chart" />`

I also tested that with in-code sample chart, and in iOS PlotView stays totally blank:

```csharp
var plotModel = new PlotModel
            {
                Title = "OxyPlot in Xamarin.Forms",
                Subtitle = string.Format("OS: {0}, Idiom: {1}", Device.OS, Device.Idiom),
                Background = OxyColors.LightYellow,
                PlotAreaBackground = OxyColors.LightGray
            };
            var categoryAxis = new CategoryAxis { Position = AxisPosition.Bottom };
            var valueAxis = new LinearAxis { Position = AxisPosition.Left, MinimumPadding = 0 };
            plotModel.Axes.Add(categoryAxis);
            plotModel.Axes.Add(valueAxis);
            var series = new ColumnSeries();
            series.Items.Add(new ColumnItem { Value = 3 });
            series.Items.Add(new ColumnItem { Value = 14 });
            series.Items.Add(new ColumnItem { Value = 11 });
            series.Items.Add(new ColumnItem { Value = 12 });
            series.Items.Add(new ColumnItem { Value = 7 });
            plotModel.Series.Add(series);

            this.MainPage = new ContentPage
            {
                Padding = new Thickness(0, 20, 0, 0),
                Content = new PlotView
                {
                    Model = plotModel,
                    VerticalOptions = LayoutOptions.Fill,
                    HorizontalOptions = LayoutOptions.Fill,
                },
            };
```

**Comment by adamjweaver** [comment] 2015-03-25 14:52
I came across this issue too, but manually adding the OxyPlot.Xamarin.Forms package fixed it. Have you initialised the renderer in your AppDelegate? I tried not initialising and I got a blank view as you described.

**Comment by tibel** [comment] 2015-03-29 07:20
I think this might be related to #363

**Comment by tibel** [comment] 2015-04-11 07:44
Now see what the issue is: The _OxyPlot.Xamarin.Forms_ assembly is missing in the platform folders:
![oxyplot_xamarin_forms_nuget](https://cloud.githubusercontent.com/assets/387395/7100671/50ed7b6e-e02f-11e4-9eec-9ab66fac6f62.PNG)

**Comment by tibel** [comment] 2015-04-11 10:38
@objorke I've updated the nuspec and all build scripts. Don't know which ones are used or not. May you try if you can build and publish the packages?

**Comment by objorke** [comment] 2015-04-16 09:15
This should be solved in the OxyPlot.Xamarin.Forms 2015.1.840-alpha package. @kevinash can you please confirm and close this issue?

**Closed** 2015-05-14 05:08 UTC
Labels: NuGet, please-verify, Xamarin.Forms
