### ISSUE TITLE
'tt' FormatString not returning expected result for TimeSpanAxis

### ISSUE THREAD

**Issue by pltaylor** [oxyplot/oxyplot#528] opened 2015-07-07 12:09 UTC
The following code should produce a time with AM/PM after the time in a 12 hour format, but it produces an axis with a 24 hour format and the letters 'tt' after it.

xAxis = new OxyPlot.Axes.TimeSpanAxis
                    {
                        MaximumPadding = 0,
                        MinimumPadding = 0,
                        MajorGridlineStyle = LineStyle.None,
                        MinorGridlineStyle = LineStyle.None,
                        StringFormat = "h:mm tt",
                        Position = AxisPosition.Bottom
                    };

![image](https://cloud.githubusercontent.com/assets/986333/8545742/7a8d7908-247f-11e5-9627-9c2414633833.png)

**Comment by tibel** [comment] 2015-07-08 08:00
Duplicate of #330

**Closed by tibel** 2015-07-08 08:00 UTC
Labels: duplicate
