### ISSUE TITLE
OxyPlot not shown when deploying to  device

### ISSUE THREAD

**Issue by david-laundav** [oxyplot/oxyplot#492] opened 2015-05-16 13:21 UTC
When deploying OxyPlot to a physical iOS device using Ad-Hoc distribution or launching to the App Store, OxyPlot is for some reason not being displayed.

The graphs are being displayed just fine when simply debugging.

OxyPlot: 2015.1.859
Xamarin.Forms: 1.4.2.6359

**Comment by david-laundav** [comment] 2015-05-16 14:03
Also note that I have just recently updated to the newest version of Xamarin.iOS

**Comment by david-laundav** [comment] 2015-05-16 14:36
Hmm.. I think this may have something to do with the new version of Xamarin.iOS.
I have also tried with Xamarin.Forms 1.4.1.6349 and 1.4.0.6341 with no success - the graphs are not shown at all, even in a new project where I am using the following sample:

https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/Xamarin.Forms/SimpleDemo/SimpleDemo/App.cs

**Comment by david-laundav** [comment] 2015-05-16 15:28
Yeah, so I downgraded to Xamarin.iOS 8.9.1 (Apr 13, 2015) and Xamarin Studio 5.8.3 (Apr 14, 2015), cleaned my build, deleted the bin/obj folders, and built the project for Ad-Hoc again. By now, the graphs have appeared again.

So this means, that there is an issue when building/deploying to a physical iOS device when using >= Xamarin.iOS 8.10 (Apr 29, 2015) and Xamarin.Studio 5.9.1 (May 13, 2015)

**Comment by tibel** [comment] 2015-05-18 10:16
So is this a Xamarin or OxyPlot issue?
If it is Xamarin it should be reported to them.

**Comment by david-laundav** [comment] 2015-05-18 11:08
I am not sure. I just looked through their release notes for Xamarin.iOS 8.10, where I did not find anything of particular interest:
http://developer.xamarin.com/releases/ios/xamarin.ios_8/xamarin.ios_8.10/

Maybe you could have a look at the release notes, @tibel (or @objorke), to see if there is anything which has popped up that we need to handle?

Thanks

**Comment by jgold6** [comment] 2015-05-28 00:42
Hi,

I am on the Xamarin support team. I just had a customer report this to us. I however was not able to make the graph show on iOS even with Xamarin.iOS 8.9.1 (April 13, 2015) and Xamarin Studio (5.8.3 April 14, 2015) using the sample code from SimpleDemo noted above. And this was deploying to a simulator, not device. 

I also tested a non-Forms iOS app and running the OxyPlot sample included with the Xamarin Component did show the graphs on an iOS Simulator and device running the latest stable of Xamarin.iOS (8.10) and Xamarin Studio (5.9.1), so this seems exclusive to Xamarin.Forms apps. I note you are still in Alpha for your Forms packages, as such I do not plan to investigate further at this point. If you do feel it is a bug with Xamarin Forms or Xamarin iOS, please file a bug report at bugzilla.xamarin.com. 

Thanks!

**Comment by robertmiles3** [comment] 2015-06-05 21:16
@david-laundav @tibel Just had this issue as well (worked in sim but not on device) and finally got it working. I kept comparing my Debug config profile vs. the Ad-Hoc I was using for device. It finally worked when I switched the Ad-Hoc's "Supported architectures" mode from "ARMv7 + ARM64" to just "ARMv7". That makes me wonder if OxyPlot is not liking 64-bit ARM64 architecture for some reason.

**Comment by david-laundav** [comment] 2015-06-09 19:51
@robertmiles3 Thanks for reporting your observation! Unfortunately, the approach won't solve much, as Apple, since June 1, [requires 64-bits comptability](https://developer.apple.com/news/?id=04082015a), meaning that the app would be rejected.

**Comment by robertmiles3** [comment] 2015-06-09 19:52
@david-laundav Yep, correct. Fortunately, my scenario is an Enterprise app so I can still go 32-bit. :)

**Comment by david-laundav** [comment] 2015-06-09 19:59
@robertmiles3 Ah, I see. It also wouldn't be an issue for Android, I assume. But certainly, this has to be fixed, and if it's due to the 64-bit architecture, we're one step closer to finding the issue.

@objorke Do you know whether or not we support 64-bit architecture for Xamarin.Forms? And would you know what would we would need to fix to actually support it? The issue seems odd, since 64-bit *seemingly* was supported since the last updated, since the [Unified API](http://developer.xamarin.com/guides/cross-platform/macios/unified/) was added long ago.

**Comment by tibel** [comment] 2015-06-09 20:28
@david-laundav OxyPlot does not contain any native code.
Maybe some weird compiler bug?

**Comment by objorke** [comment] 2015-06-10 04:40
@david-laundav Sorry, I don't know. But we should support 64-bit! Sorry, I cannot contribute more at the moment.

**Comment by tibel** [comment] 2015-06-10 17:21
Does it happen with _OxyPlot.Xamarin.iOS_ projects (without _Xamarin.Forms_) too?
Or is the issue _OxyPlot.Xamarin.Forms_ only?

**Comment by jgold6** [comment] 2015-06-10 18:00
Earlier (comment above) I confirmed that OxyPlot works with a non-Forms Xamarin.iOS app project, but this uses a different package, yes? 
So the issue seems to be OxyPlot Xamarin.Forms only.

**Comment by HippoBaro** [comment] 2015-06-11 00:48
I'm facing the same problem on my app.
When I set targeted architectures to ARMv7, ARMv7s or ARM64 the graphs are displayed correctly on device.
But if I select ARMv7+ARM64 (any FAT configuration in fact), it doesn't work.

Note that if I chose to not link at all, it works no matters the targeted architecture(s).
It's seems to be a linking problem from me.

**Comment by david-laundav** [comment] 2015-06-11 17:55
@HippoBaro Hm, sounds plausible.

Maybe [mtouch removes/garbage collects some library](http://developer.xamarin.com/guides/ios/advanced_topics/linker/) which shouldn't be removed? [I had a similar issue before with Android and Json.NET](http://forums.xamarin.com/discussion/30702/beta-json-net-crashing-in-release-mode), where Json.NET crashed in release-mode since System.Core was garbage collected.

**Comment by HippoBaro** [comment] 2015-06-11 21:22
Perhaps, anyway this is not an Oxyplot problem in my opinion, but rather a Xamarin one.
Did you open a ticket there ?

**Comment by robertmiles3** [comment] 2015-06-12 18:01
I just submitted a bug report to Xamarin since it looks like it's leaning toward a Xamarin issue.

https://bugzilla.xamarin.com/show_bug.cgi?id=31076

**Comment by HippoBaro** [comment] 2015-07-01 06:16
From bugzilla : You can force mtouch linker to include OxyPlot renderer with :
```C#
new global::OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer();
```

**Comment by tibel** [comment] 2015-07-08 08:24
@mattleibow Any news on this?

**Comment by kevinash** [comment] 2015-07-16 20:45
I confirm the issue: Ad-Hoc or AppStore don't show OxyPlot view... OxyPlot Xamarin Forms needs fixing (specifically OxyPlot Xamarin iOS):

1) Broken all latest alphas
2) Broken Ad-Hoc and AppStore version of earlier alphas

**Comment by vgvassilev** [comment] 2015-08-09 16:37
I am still experiencing the same issue.

**Comment by tibel** [comment] 2015-08-09 17:49
@mattleibow I assign the issue to you. Only to track somehow, that we are waiting for feedback/info from Xamarin.

**Comment by vgvassilev** [comment] 2015-08-09 18:07
Just to sum things up:
* I confirm that the same code works on Android.
* I see the issue both on Debug and Release mode with linker behavior "Don't link".
* I am not sure how to apply the suggested by Xamarin fix, since I need to add as a reference the platform-specific ```OxyPlot.Xamarin.iOS.dll```.

If there is anything else I can do to work the issue I'd be happy to try!

**Comment by kevinash** [comment] 2015-08-13 17:40
I tried downloading OxyPlot project from Github and building SimpleDemo.iOS in Debug and Add-Hoc mode (Xamarin). I also updated all project references. It shows chart in Debug but the demo is blank (completely, blank screen) in Ad-Hoc. When apps are built in Xamarin you debug in Debug, and deploy to the store in AppStore configuration. Unfortunately you cannot deploy AppStore configuration to device so people use Ad-Hoc instead. Basically as a result of that: apps with OxyPlot show charts in Debug build but show NOTHING when deployed to Apple Store. 

 

Then I tried hard linking .DLLs from OxyPlot.Xamarin.Forms.Platform.iOS to SimpleDemo.iOS (both from Debug and Ad-Hoc build: no matter what SimpleDemo.iOS shows blank screen in Ad-Hoc).

 

/Kevin

**Comment by kevinash** [comment] 2015-08-13 17:51
Confirmed that with “Do not link” for iOS app, even Ad-Hoc works, but why doesn’t it work with linker assembly option “SDK assemblies only” which is Xamarin default?

 

http://developer.xamarin.com/Guides/ios/Advanced_Topics/Linker/

 

From Xamarin:

“Disabling linking will make sure that no assemblies are modified. For performance reasons this is the default setting when your IDE targets for the iOS simulator. For devices builds this should only be used as a workaround whenever the linker contains a bug that prevents your application to run. If your application only works with -nolink, please submit a bug report <http://bugzilla.xamarin.com/> .

This correspond to the -nolink option when using the command-line tool mtouch.”

 

 

From: Kevin Ashley [mailto:kevinash@outlook.com] 
Sent: Thursday, August 13, 2015 10:40 AM
To: 'oxyplot/oxyplot' <reply@reply.github.com>; 'oxyplot/oxyplot' <oxyplot@noreply.github.com>
Subject: RE: [oxyplot] OxyPlot not shown when deploying to device (#492)

 

I tried downloading OxyPlot project from Github and building SimpleDemo.iOS in Debug and Add-Hoc mode (Xamarin). I also updated all project references. It shows chart in Debug but the demo is blank (completely, blank screen) in Ad-Hoc. When apps are built in Xamarin you debug in Debug, and deploy to the store in AppStore configuration. Unfortunately you cannot deploy AppStore configuration to device so people use Ad-Hoc instead. Basically as a result of that: apps with OxyPlot show charts in Debug build but show NOTHING when deployed to Apple Store. 

 

Then I tried hard linking .DLLs from OxyPlot.Xamarin.Forms.Platform.iOS to SimpleDemo.iOS (both from Debug and Ad-Hoc build: no matter what SimpleDemo.iOS shows blank screen in Ad-Hoc).

 

/Kevin

**Comment by kevinash** [comment] 2015-08-13 22:16
The ‘magic’ way to fix it is by adding another renderer in IOS project derived from PlotViewRenderer. Otherwise, linker strips OxyPlot PlotViewRenderer

 

http://forums.xamarin.com/discussion/39525/xamarin-linker-sdk-only-targeting-ios-fails-under-release

 

with the following code added to SimpleDemo.iOS, charts work again in Ad-Hoc mode. Not the ideal solution! Because every app needs to add this fix.

 

using OxyPlot.Xamarin.Forms.Platform.iOS;

using System;

using System.Collections.Generic;

using System.Text;

using Xamarin.Forms.Platform.iOS;

 

namespace SimpleDemo.iOS

{

    public class OxyPlotViewRenderer : PlotViewRenderer

    {

        protected override void OnElementChanged(ElementChangedEventArgs<OxyPlot.Xamarin.Forms.PlotView> e)

        {

            base.OnElementChanged(e);

        }

        protected override void OnElementPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)

        {

            base.OnElementPropertyChanged(sender, e);

        }

    }

 

}

 

From: Kevin Ashley [mailto:kevinash@outlook.com] 
Sent: Thursday, August 13, 2015 10:51 AM
To: 'oxyplot/oxyplot' <reply@reply.github.com>; 'oxyplot/oxyplot' <oxyplot@noreply.github.com>
Subject: RE: [oxyplot] OxyPlot not shown when deploying to device (#492)

 

Confirmed that with “Do not link” for iOS app, even Ad-Hoc works, but why doesn’t it work with linker assembly option “SDK assemblies only” which is Xamarin default?

 

http://developer.xamarin.com/Guides/ios/Advanced_Topics/Linker/

 

From Xamarin:

“Disabling linking will make sure that no assemblies are modified. For performance reasons this is the default setting when your IDE targets for the iOS simulator. For devices builds this should only be used as a workaround whenever the linker contains a bug that prevents your application to run. If your application only works with -nolink, please submit a bug report <http://bugzilla.xamarin.com/> .

This correspond to the -nolink option when using the command-line tool mtouch.”

 

 

From: Kevin Ashley [mailto:kevinash@outlook.com] 
Sent: Thursday, August 13, 2015 10:40 AM
To: 'oxyplot/oxyplot' <reply@reply.github.com>; 'oxyplot/oxyplot' <oxyplot@noreply.github.com <mailto:oxyplot@noreply.github.com> >
Subject: RE: [oxyplot] OxyPlot not shown when deploying to device (#492)

 

I tried downloading OxyPlot project from Github and building SimpleDemo.iOS in Debug and Add-Hoc mode (Xamarin). I also updated all project references. It shows chart in Debug but the demo is blank (completely, blank screen) in Ad-Hoc. When apps are built in Xamarin you debug in Debug, and deploy to the store in AppStore configuration. Unfortunately you cannot deploy AppStore configuration to device so people use Ad-Hoc instead. Basically as a result of that: apps with OxyPlot show charts in Debug build but show NOTHING when deployed to Apple Store. 

 

Then I tried hard linking .DLLs from OxyPlot.Xamarin.Forms.Platform.iOS to SimpleDemo.iOS (both from Debug and Ad-Hoc build: no matter what SimpleDemo.iOS shows blank screen in Ad-Hoc).

 

/Kevin

**Comment by vgvassilev** [comment] 2015-08-14 09:18
Thanks for the suggestion. I tried it and I get:
```...src/app/iOS/OxyPlotViewRenderer.cs(73,73): Error CS0012: The type `OxyPlot.Xamarin.iOS.PlotView' is defined in an assembly that is not referenced. Consider adding a reference to assembly `OxyPlot.Xamarin.iOS, Version=2015.1.889.0, Culture=neutral, PublicKeyToken=null' (CS0012) (App.iOS)```

I can find PlotView defined in OxyPlot.Xamarin.Forms.dll It seems that somehow the lookup is overruled by OxyPlot.Xamarin.iOS.

**Comment by vgvassilev** [comment] 2015-08-14 12:18
After a few setup issues that IMO have nothing to do with oxyplot I managed to workaround the problem. It can be either the suggested custom renderer or the one liner:
```var dummy = typeof(OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer);``` in the AppDelegate.cs
Thanks!

**Comment by objorke** [comment] 2015-10-13 04:59
Is this issue solved?
Please re-try with the latest pre-release NuGet package.

**Comment by objorke** [comment] 2015-10-20 20:33
@david-laundav was this issue solved?
should the "initialization" of the PlotViewRenderer be changed? Is it being optimized away when buildinf for ad-hoc or the app store? 

I see three options listed here
- `OxyPlot.Xamarin.Forms.Platform.iOS.Forms.Init()`
- `var dummy = typeof(OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer)`
- `new global::OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer()`

**Comment by david-laundav** [comment] 2015-10-27 22:37
@objorke Sorry, I've been really busy as of late, so havn't had time to test with the new releases. Not sure exactly when I will have time.

I think you're spot on, although. The compiler seems to optimise away the type reference.
Unfortunately, I am unable to see how the three different options differ. Which solution would you suggest? Others, including myself, are using the third option right now, but declare it as a public static field in AppDelegate. 
It'd be awesome if we could handle this issue in the library, so other developers wouldn't have to handle the issue manually - or at least not knowingly (I guess that's why you suggested the first option?).

**Comment by objorke** [comment] 2015-10-28 20:27
Is there a 'best practice' for Xamarin.Forms components on how to do this?
I see the third option is also used in:
https://blog.xamarin.com/visualize-your-data-with-charts-graphs-and-xamarin-forms/

**Comment by objorke** [comment] 2015-10-28 20:34
Could we add some code in the init() method that does not really do anything, but will never be optimized away? Thread.Sleep(1)? Trace.Write("")?
Or better: Set an "initialized" flag on the PlotView? This should then be checked when trying to instantiate a PlotView. I will create a branch to test this out...

**Comment by objorke** [comment] 2015-10-28 22:37
What do you think about #639 - this will enforce option 1...

**Comment by david-laundav** [comment] 2015-10-29 11:08
@objorke Sure, it's a breaking change, but I think that throwing an exception when the renderer is not initialized is the correct way to handle this issue. 

Normally, if the service hasn't been initialized when using either IoC or DependencyService, an exception will also be thrown.

So conclusively, option 1 is certainly the best solution seen from my point of view. 
We could also consider developing OxyPlot.Xamarin.Forms as a "service" so it would have to be resolved either using the DepecencyService or IoC.

**Comment by objorke** [comment] 2015-10-29 21:35
I also added the Init in the static constructor of the renderer, then both option 1 and 3 should be supported.

Is it possible to get IoC/DependencyService to work with the changes in #639? I think the dependency needs to be resolved, otherwise the Init() method will not be called and the PlotView will throw the exception... Should I add an `IPlotViewRenderer` interface for IoC?

**Comment by david-laundav** [comment] 2015-10-29 21:50
Well, as I see it, either we use the `Init()` approach or the IoC/DepedencyService approach. Or should we support both? I think that may cause confusion? 

But yes, if we were to support IoC/DepedencyService as well, then we would need to add an `IPlotViewRenderer` interface which can be resolved.

**Comment by objorke** [comment] 2015-10-29 21:52
The advantage with the Init approach is that we can throw an exception in the PlotView if it has been forgotten. I don't see any way to do this with the IoC approach.

**Comment by david-laundav** [comment] 2015-10-29 22:36
Let's go with using `Init()`. I think that's the best solution as well for now. Then we can investigate `IoC` at a later point if needed be.

**Comment by objorke** [comment] 2015-11-04 18:37
OK. I have merged #639 - A call to `PlotViewRender.Init()` is now the recommended way, `Forms.Init()` is marked obsolete (to avoid confusion with `Xamarin.Forms.Forms.Init()`). If the `Init()` method is not called, an exception will be thrown when creating a `PlotView`.

Can this issue be closed?

**Comment by david-laundav** [comment] 2015-11-08 21:41
Awesome. Good job, @objorke!

I won't get the time to test in a while. Do we have someone else who could help us to test the solution before closing?

**Comment by objorke** [comment] 2015-12-17 13:49
Will close this issue. Please re-open if the problem persists.

**Closed by objorke** 2015-12-17 13:49 UTC
Labels: confirmed-bug, high-priority, investigate, iOS, please-verify, Xamarin.Forms
