### ISSUE TITLE
mouseUp  Not triggered

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1650] opened 2020-08-27 09:16 UTC
private void Form1_Load(object sender, EventArgs e)
    {
        var model = new PlotModel()
        {
            Title = "World population by contnent",
        };

        var pie = new PieSeries()
        {
            StrokeThickness = 0.25,
            InsideLabelPosition = 0.5,
            AngleSpan = 360,
            StartAngle = 0
        };

        pie.Slices.Add(new PieSlice("Africa", 1030) { IsExploded = false, Fill = OxyColor.FromArgb(50, 20, 10, 30) });
        pie.Slices.Add(new PieSlice("Americas", 929) { IsExploded = false });
        pie.Slices.Add(new PieSlice("Asia", 4157));
        pie.Slices.Add(new PieSlice("Europe", 739) { IsExploded = false });
        pie.Slices.Add(new PieSlice("Oceania", 35) { IsExploded = false });
        model.Series.Add(pie);
        model.Series.Add(new FunctionSeries());
        plotView1.Model = model;

        clickPie(pie);
    }

    public void clickPie(PieSeries pie)
    {

        pie.MouseUp += (s, m) => { Debug.WriteLine("message"); };//Not triggered

        //
        //TrackerHitResult x;
        //pie.MouseDown += (s, m) =>
        //{
        //    x = (s as PieSeries).GetNearestPoint(m.Position, true);
        //    Debug.WriteLine(x.Text.Split(':')[0]);
        //    updateColor(x.Text.Split(':')[0], (s as PieSeries));
        //};
    }

**Comment by VisualMelon** [comment] 2020-08-27 09:27
You need to set the `Handled` property of the event args supplied to `MouseDown` in order for any following events to fire. I think that's the problem here. It's not very well documented.

**Comment by SynapseIkaros** [comment] 2020-08-28 01:04
> 您需要将提供的事件args 的`Handled`属性设置`true`为`MouseDown`，以便触发以下任何事件。我认为这就是问题所在。它没有很好的记录。
I don't understand

**Comment by SynapseIkaros** [comment] 2020-08-28 02:45
> 您需要将提供的事件args 的`Handled`属性设置`true`为`MouseDown`，以便触发以下任何事件。我认为这就是问题所在。它没有很好的记录。

How to draw a 3D circle

**Comment by VisualMelon** [comment] 2020-08-28 07:28
There is no support for 3D plots in OxyPlot. In part this is a technical concern (it has grown into a light-weight, low-maintenance, multi-platform offering), and adding 3D effects to 2D plots is rarely a good idea. OxyPlot has a history of not doing things that don't help with interpretability, and 3D Pie's are generally considered misleading. (Pie's themselves get a hammering, because, they are generally harder to read than an equivalent bar-chart, and it has been suggested they are removed from the core library).

**Comment by SynapseIkaros** [comment] 2020-08-28 07:59
> OxyPlot不支持3D图。在某种程度上，这是一个技术问题（它已经发展成为一种轻量，低维护，多平台的产品），并且在2D绘图中添加3D效果很少是一个好主意。OxyPlot的历史是不做任何对解释性无助的事情，而3D Pie通常被认为具有误导性。（Pie自己会受到重击，因为它们通常比等效的条形图更难读，并且建议将其从核心库中删除）。

Bug of mouseDown is okay, But mouseUp still doesn't triggered , But it doesn't matter,Thank you

**Comment by SynapseIkaros** [comment] 2020-08-28 08:00
> OxyPlot不支持3D图。在某种程度上，这是一个技术问题（它已经发展成为一种轻量，低维护，多平台的产品），并且在2D绘图中添加3D效果很少是一个好主意。OxyPlot的历史是不做任何对解释性无助的事情，而3D Pie通常被认为具有误导性。（Pie自己会受到重击，因为它们通常比等效的条形图更难读，并且建议将其从核心库中删除）。

**Comment by VisualMelon** [comment] 2020-08-28 08:01
To clarify, you should see `MouseUp` being trigged if you add a `MouseDown` event which sets the `Handled` property of the event args to true, e.g. 

    pie.MouseDown += (s, m) => m.Handled = true;

**Comment by SynapseIkaros** [comment] 2020-08-28 08:04
> 为了澄清，`MouseUp`如果添加一个将事件args `MouseDown`的`Handled`属性设置为true 的事件，则应该被触发，例如
> 
> ```
> pie.MouseDown += (s, m) => m.Handled = true;
> ```
> 
> 这由库检查，并确定哪个控件将接收`MouseUp`事件；如果`Handled`未设置，`MouseUp`则不发送。

 pie.MouseDown += (s, m) =>
            {
                x = (s as PieSeries).GetNearestPoint(m.Position, true);
                Debug.WriteLine(x.Text.Split(':')[0]);
                updateColor(x.Text.Split(':')[0], (s as PieSeries));
                m.Handled = true;
            };
Solved the problem that my mousedown does not lift, but it will not trigger mouseup

**Comment by VisualMelon** [comment] 2020-08-28 08:17
I'm afraid I can't reproduce this; which version of OxyPlot are you using, and which platform (WPF. WinForms, etc.)?

**Comment by SynapseIkaros** [comment] 2020-08-28 08:19
> > 为了澄清，`MouseUp`如果添加一个将事件args `MouseDown`的`Handled`属性设置为true的事件，则应该被触发，例如
> > ```
> > pie.MouseDown += (s, m) => m.Handled = true;
> > ```
> > 
> > 
> > 这由库检查，并确定其中控件将接收`MouseUp`事件；如果`Handled`未设置，`MouseUp`则不发送。
> 
> pie.MouseDown + =（s，m）=>
> {
> x =（s为PieSeries）.GetNearestPoint（m.Position，true）;
> Debug.WriteLine（x.Text.Split（'：'）[0]）;
> updateColor（x.Text.Split（'：'）[0]，（s为PieSeries））;
> m.Handled = true;
> };
> 解决了我的mousedown不能抬起但不会触发mouseup的问题



> 恐怕我无法重现。您正在使用哪个版本的OxyPlot，以及哪个平台（WPF，WinForms等）？

OxyPlot.Core 2.0 and OxyPlot。WindowsForms 2.0

**Comment by VisualMelon** [comment] 2020-08-28 08:30
Thanks. I can't reproduce it with that setup either; a breakpoint inside `MouseUp` is hit as expected.

I removed the `updateColor` call, because I don't know what it does: could you try the same? It might narrow down the problem.

I did notice that if I put a breakpoint in `MouseDown`, then the context change back to the IDE means `MouseUp` is never sent.

**Comment by SynapseIkaros** [comment] 2020-08-28 08:59
> 谢谢。我也无法使用该设置来重现它；内部的断点`MouseUp`被预期击中。
> 
> 我不`updateColor`打了电话，因为我不知道它会做什么：您能尝试同样的方法吗？这样可以缩小问题的范围。
> 
> 我确实注意到，如果在中放置了一个断点`MouseDown`，则上下文更改返回到IDE意味着`MouseUp`永远不会发送。

 public void updateColor(string name, PieSeries pie)
        {
            ColorDialog colorDia = new ColorDialog();


            if (colorDia.ShowDialog() == DialogResult.OK)
            {
                //获取所选择的颜色
                Color colorChoosed = colorDia.Color;
                //改变panel的背景色
                label1.BackColor = colorChoosed;
                OxyColor oxColor = OxyColor.FromArgb(colorChoosed.A, colorChoosed.R, colorChoosed.G, colorChoosed.B);

                for (int i = 0; i < pie.Slices.Count; i++)
                {
                    if (pie.Slices[i].Label == name)
                    {
                        pie.Slices[i] = new PieSlice(name, pie.Slices[i].Value) { IsExploded = false, Fill = oxColor };
                        break;
                    }
                }
                //PlotModel model = this.plotView1.Model;
                //plotView1.Model = model;
                plotView1.Refresh();
            }
        }

**Comment by VisualMelon** [comment] 2020-08-28 09:06
Yeah, that messes with things. `MouseUp` isn't thrown when the dialog is open, because the dialog has focus.

**Comment by SynapseIkaros** [comment] 2020-08-31 07:19
> 是的，这很混乱。`MouseUp`对话框打开时不会引发，因为对话框具有焦点。

How do I customize the size of the pie chart?

**Comment by Jonarw** [comment] 2020-09-19 07:55
Is the original question of this issue solved? Can we close this?

**Closed** 2020-09-24 02:02 UTC
