### ISSUE TITLE
LineSeries null reference exception when smoothing enabled and all datapoints have the same y value

### ISSUE THREAD

**Issue by cjmurph** [oxyplot/oxyplot#226] opened 2014-10-25 06:40 UTC
If a series is made where all the data points have the same y value (0 for example) and smoothing is enabled, GetNearestInterpolatedPointInternal returns null as there are 0 items in the SmoothedPoints collection. This results in a null reference exception being thrown when the plot is clicked.

This may occur with other series and in other scenarios, the above represents my test case.

**Comment by objorke** [comment] 2015-01-10 13:49
I cannot reproduce this exception. See new example. Can we close this issue?

**Comment by nykaz** [comment] 2015-01-20 11:18
Have exactly the same issue. Exception is raised only if the Series data is repopulated and model Invalidated (Second time).

**Comment by objorke** [comment] 2015-01-30 07:48
Can you update the example added in 4b3c488 to reproduce this bug?

**Comment by tibel** [comment] 2015-03-28 07:22
Also cannot reproduce the issue.

Anyone still having this error? What (exact) version of OxyPlot are you using on what platform?
Otherwise we should close the issue.

**Comment by tibel** [comment] 2015-03-28 15:39
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.

**Closed by tibel** 2015-03-28 15:39 UTC
Labels: easy-fix, help-wanted, high-priority, need-more-info, unconfirmed-bug, you-take-it
