### ISSUE TITLE
Xamarin Forms error MissingMethodException iOS.PlotViewRenderer

### ISSUE THREAD

**Issue by sirfilipef** [oxyplot/oxyplot#421] opened 2015-03-26 10:47 UTC
Works fine in Android.

System.MissingMethodException: Default constructor not found for type OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer

package id="OxyPlot.Core" version="2015.1.804-alpha" targetFramework="xamarinios10" 
package id="OxyPlot.Xamarin.Forms" version="2015.1.804-alpha" targetFramework="xamarinios10" 
package id="Xamarin.Forms" version="1.4.0.6341" targetFramework="xamarinios10"

**Comment by objorke** [comment] 2015-03-26 10:54
This sounds like #348

**Comment by sirfilipef** [comment] 2015-03-26 11:41
Sorry didnt understand, is this bug fixed? thanks

**Comment by objorke** [comment] 2015-03-26 11:53
Maybe the problem has been reintroduced? Do we need to update the Xamarin Forms version to 1.4.0? I think it is currently at 1.3.3

**Comment by sirfilipef** [comment] 2015-03-26 11:58
I think so, probably there is some incompatibility with the newer version of Xamarin Forms.

**Comment by kevinash** [comment] 2015-04-05 19:55
Suggesting updating for Xamarin Forms 1.4, they updated PCL profile from 78 to 259.

**Comment by tibel** [comment] 2015-04-07 20:43
@objorke Xamarin.Forms is updated to 1.4.1 would be great if you could create new nuget packages.

**Comment by objorke** [comment] 2015-04-16 09:20
@sirfilipef can you test OxyPlot.Xamarin.Forms 2015.1.840-alpha? I created two new Xamarin Forms 1.4.1.6349 apps (both portable and shared) and could not reproduce this issue.

**Comment by kevinash** [comment] 2015-04-16 11:06
Thanks! Confirmed - issue fixed in 840-alpha. Adding OxyPlot Xamarin Forms nugget package to existing shared project adds PCL library: OxyPlot.Xamarin.Forms

**Comment by kevinash** [comment] 2015-04-16 13:11
However it is still a problem in 2015.1.843-alpha

**Comment by objorke** [comment] 2015-04-16 19:56
I see the OxyPlot.Xamarin.Forms.dll assemblies are missing in 843-alpha. There is also a problem with iOS being shown as Unsupported.

**Comment by tibel** [comment] 2015-04-16 20:55
@objorke compare https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2015.1.840-alpha and https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2015.1.843-alpha
In 840 everything looks good. What is the difference in 843?

**Comment by objorke** [comment] 2015-04-16 21:35
I can only remember building 840-alpha. @mattleibow Did Xamarin build 843-alpha?

**Comment by objorke** [comment] 2015-04-17 06:02
I built and pushed 847-alpha using the "build-mobile.cmd" and "push.cmd" command files. I am using the latest stable version of NuGet.exe and Xamarin.

**Closed** 2015-05-14 05:09 UTC
Labels: iOS, please-verify, Xamarin.Forms
