### ISSUE TITLE
Oxyplot refers to HandyControl as causing graphical distortion.

### ISSUE THREAD

**Issue by BingZhao-Coder** [oxyplot/oxyplot#1649] opened 2020-08-26 04:19 UTC
Dear Sir:
    I had a problem using Oxyplot and HandyControl.
   My scenario is as follows：
   1.the example where the path is in "oxyplot-develop\Source\Examples\WPF\SimpleDemo"
   2.PerformanceTest refers to HandyControl.dll
   3.Add HandyControl Style to the file "oxyplot-develop\Source\Examples\WPF\SimpleDemo\App.xaml" and do not using any style in handyControl but just refering.
     The syntax is as follows：
    < ResourceDictionary>
            < ResourceDictionary.MergedDictionaries>
                < ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDefault.xaml" />
                < ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
            < /ResourceDictionary.MergedDictionaries>
        < /ResourceDictionary>
    4.just run the program which is "oxyplot-develop\Source\Examples\WPF\SimpleDemo" and The program was executed successfully,then the graphic is deformed.
    I have no ideal about this problem

**Comment by Jonarw** [comment] 2020-09-19 07:59
I am not quite sure what the problem is here and if we can do anything to solve this. Considering this issue is 24 days old at this point I will close this. 

Feel free to reopen if you can give some more specific information about a potential issue with the library.

**Closed by Jonarw** 2020-09-19 07:59 UTC
