### ISSUE TITLE
Helvetica not available in PDF export

### ISSUE THREAD

**Issue by FrederikTheisen** [oxyplot/oxyplot#1361] opened 2019-10-04 11:03 UTC
I'm trying to change the fonts of plotelements (legend, title and so on) to helvetica since that is the recommended font for Science Research Journals figures, however it does not seem to work. Using the OxyPlot.StandardFonts.Helvetica feature simply returns "Arial" and if I try to set the font to "Helvetica" it remains as Arial.

Im trying to do this on a Macbook which has the Helvetica Neue font family installed.

Is this the intended behavior and is it there any way I can get it to use a Helvetica family font?

Thank you.

**Comment by FrederikTheisen** [comment] 2019-10-08 13:57
As far as I can see, there are three standard font available (found in the StandardFonts class).
One of them is assigned to a property called 'Helvetica', however the fontname is called "Arial".

So this suggests that there is no Helvetica font available in the OxyPlot version I have (for Xamarin.Mac [Modern], .Net version is not clear but it is the recommended version of Xamarin.Mac).

I haven't figured out how to load a custom font or where exactly the font visual information is actually found.

**Comment by objorke** [comment] 2019-10-15 19:47
Is this an issue related to PDF export?

If the issue is related to the OxyPlot.Xamarin.Mac library, please add the issue to https://github.com/oxyplot/oxyplot-xamarin/issues

**Comment by FrederikTheisen** [comment] 2019-10-15 21:33
Well, yes it is related to pdf export, but part of the issue is that the standard font "Helvetica" contains a fontname called "Arial", which is weird considering that they are different font.

I need the Helvetica font, since it is the recommended font for use in scientific publication figures.

My OxyPlot package is simply called OxyPlot.Core version 2.0.0-unstable1035, and I can't find any package called OxyPlot.Xamarin.Mac (as opposed to Android, iOS, Forms which are visible in the NuGet browser).

**Comment by FrederikTheisen** [comment] 2019-10-22 09:48
I tried opening the exported PDF file as ascii and I found a font reference which could simply be changed to "Helvetica" (Neue) in order to get that typeface.

I don't think this is quite enough to implement Helvetica since there are a bunch of other parameters which also need to be changed (width, height and things like that). Also, I'm not sure that I can override the StandardFonts class and make the rest of OxyPlot use my implementation.

**Comment by FrederikTheisen** [comment] 2020-03-18 17:18
Was this issue addressed and if not are there any plans to address it?

**Comment by objorke** [comment] 2020-03-18 20:51
Let us try to get this fixed in v3.0

**Comment by Jonarw** [comment] 2020-04-28 13:56
Covered by #1514.

**Closed by Jonarw** 2020-04-28 13:56 UTC
Labels: bug, pdf
