### ISSUE TITLE
LineSeries with smoothing

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#78] opened 2014-08-14 22:30 UTC
**Imported from [http://oxyplot.codeplex.com/workitem/10075](http://oxyplot.codeplex.com/workitem/10075)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-09-05 07:53
Clip before smoothing 

[discussion:455534] 

<a href="https://oxyplot.codeplex.com/discussions/455534" rel="nofollow">https://oxyplot.codeplex.com/discussions/455534</a>

**Comment by IvoTops** [comment] 2015-06-08 09:42
Dear objorke,

I do not think this is a duplicate. I do not zoom as in the original issue. And also I get a different error.

Kind regards,

Ivo

**Comment by IvoTops** [comment] 2015-06-08 10:43
I looked at the code and it is missing a check for null  and it also does not return the result variable. Since I am not really githubbing I added what I think are the fixes below (two lines of code, see capital texts below between ========). I did only check LineSeries.cs and have not tested it.

        /// LINESERIES.CS - GetNearestPoint

        /// <summary>
        /// Gets the point on the series that is nearest the specified point.
        /// </summary>
        /// <param name="point">The point.</param>
        /// <param name="interpolate">Interpolate the series if this flag is set to <c>true</c>.</param>
        /// <returns>A TrackerHitResult for the current hit.</returns>
        public override TrackerHitResult GetNearestPoint(ScreenPoint point, bool interpolate)
        {
            if (interpolate)
            {
                // Cannot interpolate if there is no line
                if (this.ActualColor.IsInvisible() || this.StrokeThickness.Equals(0))
                {
                    return null;
                }

                if (!this.CanTrackerInterpolatePoints)
                {
                    return null;
                }
            }

            if (interpolate && this.Smooth && this.SmoothedPoints != null)
            {
                var result = this.GetNearestInterpolatedPointInternal(this.SmoothedPoints, point);

========== CHECK FOR NULL SHOULD BE ADDED AS RESULT CAN BE NULL
                if (result != null) 
                {
 ==========
                    result.Text = StringHelper.Format(this.ActualCulture, this.TrackerFormatString, result.Item, this.Title, this.XAxis.Title ?? XYAxisSeries.DefaultXAxisTitle, this.XAxis.GetValue(result.DataPoint.X), this.YAxis.Title ?? XYAxisSeries.DefaultYAxisTitle, this.YAxis.GetValue(result.DataPoint.Y));
========== I THINK YOU SHOULD RETURN THE RESULT HERE, NOT CALL BASE 
                    return result;
                }
==========
            }

            return base.GetNearestPoint(point, interpolate);
        }

**Comment by tibel** [comment] 2015-06-09 19:41
Seems to be a duplicate of #499

**Closed** 2015-06-09 19:42 UTC
Labels: CodePlex, confirmed-bug, duplicate, series
