### ISSUE TITLE
Exception while trying to pan before the chart is plotted

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#114] opened 2014-08-14 22:31 UTC
**Imported from [http://oxyplot.codeplex.com/workitem/10138](http://oxyplot.codeplex.com/workitem/10138)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-02-25 11:19
See <a href="https://oxyplot.codeplex.com/discussions/522598" rel="nofollow">
https://oxyplot.codeplex.com/discussions/522598</a>

**[tibel](http://www.codeplex.com/site/users/view/tibel)** 2014-03-22 11:10
Please re-test with latest version (2014.1.259.1).

**[tibel](http://www.codeplex.com/site/users/view/tibel)** 2014-04-06 08:52
Seems that this is WinForms only.

**Comment by tibel** [comment] 2015-03-28 16:27
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.

**Closed by tibel** 2015-03-28 16:27 UTC
Labels: CodePlex, help-wanted, high-priority, need-more-info, unconfirmed-bug

**Comment by chaselal** [comment] 2017-11-06 20:11
I was able to reproduce this on a build of [this fork commit](https://github.com/trainerroad/oxyplot/commit/343c02ff0e021374bf1aa0f2104a0f922864ad94), which is 7 unrelated commits ahead of `oxyplot/oxyplot` and 2 commits behind (although those 2 are just touched-up cherry-picks from the same fork). I can reproduce it consistently in our Xamarin.Forms (for Android) app. Steps:
* Display a PlotView. Set up a two-way binding to that PlotView's Model property.
* Change the bound PlotModel value every one second. Don't forget INotifyPropertyChanged events. Ensure this happens on the UI thread.
* Repeatedly tap the plot very quickly.
Stack trace
```
 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#	Annotated Frame
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#	Annotated Frame
 	0x27 in object.4b4b8389-46f8-4d14-bbbb-0226548fbbf2	C#	Annotated Frame
 	0x1B in OxyPlot.Series.XYAxisSeries.InverseTransform	C#	Annotated Frame
 	0x3 in OxyPlot.Series.AreaSeries.GetNearestPoint	C#	Annotated Frame
 	0x9 in OxyPlot.Series.Series.HitTestOverride	C#	Annotated Frame
 	0x3 in OxyPlot.UIElement.HitTest	C#	Annotated Frame
 	0x74 in OxyPlot.Model.HitTest	C#	Annotated Frame
 	0x56 in OxyPlot.Model.HandleTouchStarted	C#	Annotated Frame
 	0x2B in OxyPlot.ControllerBase.HandleTouchStarted	C#	Annotated Frame
>	0x16 in OxyPlot.Xamarin.Android.PlotView.OnTouchDownEvent at C:\Users\Chase\oxyplot-xamarin\Source\OxyPlot.Xamarin.Android\PlotView.cs:370,13	C#	Symbols loaded.
 	0x2F in OxyPlot.Xamarin.Android.PlotView.OnTouchEvent at C:\Users\Chase\oxyplot-xamarin\Source\OxyPlot.Xamarin.Android\PlotView.cs:297,25	C#	Symbols loaded.
 	0x11 in Android.Views.View.n_OnTouchEvent_Landroid_view_MotionEvent_	C#	Annotated Frame
```
I was not able to reproduce this on a build of a very old version of OxyPlot from before the `oxyplot`/`oxyplot-xamarin` project split.
