### ISSUE TITLE
Palette of HeatMap's ColorAxis is wrong after updating the Data of which elements are all of a common value

### ISSUE THREAD

**Issue by micheldauros** [oxyplot/oxyplot#2004] opened 2023-06-05 10:39 UTC
### Steps to reproduce

1. 
Environment: WPF version 2.1.2.0
Here's the partial code sample

```
//In ViewModel.cs
public ViewModel{
var colorAxis = new LinearColorAxis
            {
                Palette = OxyPalettes.Rainbow(10),
            };
            Model.Axes.Add(colorAxis);
            Data=new double[,] { { 0, 0, 0.0 }, { 0, 0, 0 }, { 0, 0, 0 } };
            //Use below data for comparison
            //Data=new double[,] { { 6, 1, 7.0 }, { 3,4, 9 }, { 8, 2, 5 } };
            var series = new HeatMapSeries
            {
                X0 = 0,
                X1 = 3,
                Y0 = 0, Y1 = 3,
                Data = Data,
            };
            Model.Series.Add(series);
}

//in MainWindow.xaml.cs
private void Button_Click(object sender, RoutedEventArgs e)
        {
            var series = (HeatMapSeries)(model.Model.Series[0]);
            series.Data= new double[,] { { 3, 2, 1 }, { 4, 5, 6 }, { 8, 9, 7 } };
            model.Model.InvalidatePlot(false);
        }

```
2. If you use all zeros data in the constructor, the color is full green since green is 5th color of the palette.
3. Click the button to update the Data, the color is full red.
4. If you use the comparison Data in constructor,  the color is the rainbow color.
5.  Click the button to update the Data, the color  is still the rainbow color.

Platform:
.net framework 4.8.2

### Expected behaviour
The Data and Palette are the same in step 3 and step 5. But the 3rd step displays the wrong color. I think it should be the same as step5.
Besides, I have another program in which the Data is of about 300*300 size, the colors displays in step 3 starts from red and ends in green. It uses exactly first half of colors in the the Rainbow Palette.

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!
![step2](https://github.com/oxyplot/oxyplot/assets/26990766/d21e583b-0285-4b64-a3c6-4cbbf15872db)
![step3_allzeros](https://github.com/oxyplot/oxyplot/assets/26990766/f28d7f97-5e6a-452b-a8fd-338f1ad8bd04)
![step4](https://github.com/oxyplot/oxyplot/assets/26990766/5f8b92c7-20f4-4ca8-be5c-85c983235b7a)
![step5](https://github.com/oxyplot/oxyplot/assets/26990766/4eb0b317-3e0d-498f-a9b7-3eb3eca3961a)

**Comment by micheldauros** [comment] 2023-06-05 10:44
@VisualMelon Can you help? Do you this is the expected behavior of Heatmap Series? Thanks!

**Comment by VisualMelon** [comment] 2023-06-05 12:53
Might just be that you need to use `InvalidatePlot(true)`: the `true` signals the data may have changed (`false` is generally fine for e.g. changing the axis ranges, or what colour stuff is, or adding an annotation). If it's not that, I should have time to take a proper look tomorrow.

**Comment by micheldauros** [comment] 2023-06-06 01:03
@VisualMelon ```InvalidatePlot(true)``` make sense, you're right, thank you!

**Comment by VisualMelon** [comment] 2023-08-16 10:30
Closing, because I think this is the expected behaviour. Please do comment/reopen if anyone thinks there is an underlying problem here.

**Closed as completed by VisualMelon** 2023-08-16 10:30 UTC
