### ISSUE TITLE
OxyPlot.Xamarin.Forms cannot AOT the assembly

### ISSUE THREAD

**Issue by kevinash** [oxyplot/oxyplot#520] opened 2015-06-30 21:43 UTC
Building any project referencing OxyPlot for Xamarin Forms (889-alpha, 873-alpha)   fails for iOS: OxyPlot.Xamarin.Forms cannot AOT the assembly

**Comment by tibel** [comment] 2015-07-01 06:51
Duplicate of #479 ?

**Comment by kevinash** [comment] 2015-07-01 11:13
Yes, but it was fixed in alphas prior to those mentioned in the last issue report. It reappeared again in the latest alphas. Unfortunately OxyPlot no longer builds for Xamarin Forms IOS.
________________________________

**Comment by tibel** [comment] 2015-07-01 11:48
There were no changes on OxyPlot side. There seems to be an issue in Xamarin (see  #492).

**Comment by tibel** [comment] 2015-10-07 09:15
Please re-try with OxyPlot.Xamarin.Forms 1.0.0-unstable1849

**Comment by objorke** [comment] 2015-10-13 04:57
Please re-try with the latest pre-release NuGet package.
Can we close this issue? All demos seem to work fine.

**Closed** 2015-12-17 13:48 UTC
Labels: help-wanted, high-priority, iOS, please-verify, unconfirmed-bug, Xamarin.Forms
