### ISSUE TITLE
Dispose brushes in PNG exporters

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1392] opened 2019-10-18 20:15 UTC
### Steps to reproduce

1. Export PNG to stream

Platform: Winforms, Core.Drawing

### Expected behaviour

Brushes should be disposed

### Actual behaviour

Brushes not disposed?

**Comment by objorke** [comment] 2019-10-18 20:16
#1391

**Comment by objorke** [comment] 2019-10-18 20:18
#822 Is this related?

**Comment by VisualMelon** [comment] 2019-10-18 20:22
I don't think this is relevant, but I'll have a go at reproducing #822 to confirm.

**Comment by VisualMelon** [comment] 2019-10-18 20:49
Nope, I can't reproduce #822 under various configurations (feels like I've tried and failed before). WPF brushes shouldn't need disposal (and there is no mechanism by which we can accelerate their demise), so I think this can be closed since #1391 is merged.

**Closed** 2019-10-18 21:50 UTC
Labels: Core Drawing, Windows Forms, bug, png
