### ISSUE TITLE
Colum items not rendered properly when using a logarithmic Y axis

### ISSUE THREAD

**Issue by G30rges** [oxyplot/oxyplot#740] opened 2016-01-18 12:35 UTC
As discussed there: http://discussion.oxyplot.org/topic/1041311-colum-items-not-rendered-properly-when-using-a-logarithmic-y-axis/#

In the oxyplot sample, there are two demos making use of Bars and Columns: BarSeriesDemo and ColumnSeriesDemo.
For the first, using a logarithmic axis in place of the linear one as Y axis does not cause any problem, the values are displayed correctly:

![image](https://cloud.githubusercontent.com/assets/16758846/12391434/08717326-bde8-11e5-85d6-9d124c4429ea.png)

However, when doing the same with the demo ColumnSeriesDemo, the bars are not drawn correctly it seems, looks like they are "reversed":
In the class ColumnSeriesDemo.MainWindow, I changed the lines 43 and 44 from
tmp.Axes.Add(new CategoryAxis { ItemsSource = this.Items, LabelField = "Label" });
tmp.Axes.Add(new LinearAxis { Position = AxisPosition.Left, MinimumPadding = 0, AbsoluteMinimum = 0 });
To

tmp.Axes.Add(new CategoryAxis { Position = AxisPosition.Bottom, ItemsSource = this.Items, LabelField = "Label" });
tmp.Axes.Add(new LogarithmicAxis { Position = AxisPosition.Left, Minimum = 1, Base = 10 });

With code behind:
![image](https://cloud.githubusercontent.com/assets/16758846/12391450/26b53908-bde8-11e5-8a5a-7ee2d80a1390.png)

With xaml, without the log Y axis:
![image](https://cloud.githubusercontent.com/assets/16758846/12391452/2c34e482-bde8-11e5-81e7-9bc80b445bb8.png)

Why doesn't it behave the same way?

**Comment by G30rges** [comment] 2016-01-18 13:56
For my bars to display "properly", I have to set a base Value = 1 on the series. The problem is I might have values < 1, then they don't get displayed..

**Comment by G30rges** [comment] 2016-02-02 16:22
Does your commit fix the bug?

Cheers

**Comment by objorke** [comment] 2016-02-02 21:30
No, it was just adding your example reproducing the bug.

**Comment by Codebeisser** [comment] 2017-12-20 09:02
The same issue occurs with stem plot.

**Comment by udaykolluru** [comment] 2019-12-10 09:33
@objorke    i tried with different graphs with logarithmic axis for  area, line, scatter, i can also see the same issue ,is there any fix ,or quick fix for this .

**Comment by VisualMelon** [comment] 2019-12-10 11:26
@udaykolluru which issue exactly? Line, scatter, and 2-line area series should be fine, since they don't need a base-line. It sounds like you may have a different problem: could you provide some example code?

<hr />

The behaviour described above is certainly inconsistent (which isn't ideal), but logarithmic scales don't have a natural finite zero. Area plots (of which histograms and column plots are different types) usually don't make sense with a logarithmic y-axis, because the area always has to be relative to some baseline.

I'd expect the default behaviour to be that the bar goes on to -infinity (which the data probably is, and is probably causes issues with different renderers: e.g. WPF 'inverting' large and small values is a common symptom), but that's basically of no use to anyone: you need to pick a meaningful baseline; if you don't have a meaningful baseline, then you should probably reconsider using a chart with an area.

Some more commentary on column charts with logarithmic scale can be found in the [graph pad guide](https://www.graphpad.com/guides/prism/7/user-guide/index.htm?)bar_graphs_with_a_log_y_axis.htm

**Comment by swethakini-ofc** [comment] 2020-08-07 12:06
@VisualMelon  @objorke  I was trying LogarithmicAxis with HistogramSeries in latest Oxyplot 2.0. The graph looks inverted. How can this be corrected?
![image](https://user-images.githubusercontent.com/60653002/89643910-6a852b00-d8d4-11ea-96c2-b4b3fe45afc1.png)

**Comment by VisualMelon** [comment] 2020-08-07 12:19
@swethakini-ofc `HistogramSeries` always uses a base value of zero, so it can't be fixed: what is happening is that `log(0)` is positive infinity. I don't think it makes any sense to use a histogram on a non-linear axis, because the area and height are both meaningful quantities, but if you can explain a use case where a non-zero base would make sense, maybe we could extend it.

**Comment by swethakini-ofc** [comment] 2020-08-08 10:47
@VisualMelon What about Column Series. Even excel provides logarithmic scale for Y axis
![image](https://user-images.githubusercontent.com/60653002/89708145-3ff9a780-d992-11ea-829f-6f92c6331a7e.png)

Excel
![image](https://user-images.githubusercontent.com/60653002/89708207-8e0eab00-d992-11ea-9960-4eb21063693c.png)

**Comment by VisualMelon** [comment] 2020-08-08 11:01
@swethakini-ofc with column series, you can set the `BaseValue` to 1 in order to achieve that.

**Comment by swethakini-ofc** [comment] 2020-08-08 13:44
@VisualMelon  Thanks this worked 👍

**Closed** 2022-08-13 08:58 UTC
Labels: series, bug
