### ISSUE TITLE
HitTracker IndexOutOfRange exception

### ISSUE THREAD

**Issue by UndisputedBasement33** [oxyplot/oxyplot#1524] opened 2020-04-29 14:09 UTC
I use Oxyplot in a WPF app with C#. (v.2.0.0)

I have several plots that show a Heatmap overlaid by a contour series. My app doesn't start in fullscreen-mode so the charts are rather small. If i click into the heatmap the tracker shows the values. But sometime if I go close to the edge of the plotarea it can happen that I get an exception:
System.IndexOutOfRangeException: 'Der Index war außerhalb des Arraybereichs.'

This causes my app to crash and I have to restart it.

If I change to fullscreen mode, so bigger charts, I can't reproduce this error.
How can I help to find the root for this error? Since the error is occuring in the oxyplot code I can't debug and I have no log.
I can reproduce the error also without the contour series, so it's probably coming from the heatmap.

Thank you

**Comment by VisualMelon** [comment] 2020-04-29 14:17
Can you provide any more of a stack-trace?

It is probably floating point discrepancies between `IsPointInRange` and the rest of `GetNearestPoint`: it should check the integer coordinates before querying the data.

If you can provide an example, I'll try to verify the problem and solution.

**Comment by UndisputedBasement33** [comment] 2020-04-29 15:14
Ok I build an example, whith which I'm able to reproduce the error:

```
using OxyPlot;
using OxyPlot.Axes;
using OxyPlot.Series;
using System;
using System.Collections.Generic;

namespace WpfApp1 {
    public class ShellViewModel : Caliburn.Micro.PropertyChangedBase, IShell 
    {

        private PlotModel Plot00 { get; set; }
        public PlotModel[] PlotModels { get; set; } = new PlotModel[1];

        public List<string> XAxisLabels { get; set; } = new List<string>() { "1", "2", "3", "4", "5", "1", "2", "3", "4", "5" };
        public List<string> YAxisLabels { get; set; } = new List<string>() { "1", "2", "3", "4", "5", "1", "2", "3", "4", "5" };

        public ShellViewModel()
        {
            Plot00 = new PlotModel { Title = "This is a very long sample title, that exceeds the window limits" };
            PlotModels[0] = Plot00;

            List<OxyColor> jetTransparent = new List<OxyColor>();
            foreach (var item in OxyPalettes.Jet(1000).Colors)
            {
                jetTransparent.Add(OxyColor.FromAColor(220, item));
            }
            OxyPalette myPalette = new OxyPalette(jetTransparent);

            foreach (PlotModel plotModel in PlotModels)
            {
                plotModel.PlotAreaBackground = OxyColors.White;
                plotModel.DefaultFontSize = 14;
                //plotModel.DefaultColors = SeriesColors;
                plotModel.Padding = new OxyThickness(0);
                plotModel.TitlePadding = 0;


                plotModel.Axes.Add(new CategoryAxis
                {
                    Position = AxisPosition.Bottom,
                    Key = "HorizontalAxis",
                    ItemsSource = XAxisLabels,
                    MajorGridlineColor = OxyColors.Black,
                    MajorGridlineStyle = LineStyle.Solid,
                    IsZoomEnabled = false,
                    IsPanEnabled = false,
                    Angle = -45,
                    FontSize = 14,
                    TitleFontSize = 14,
                    AxisTitleDistance = 0
                });

                plotModel.Axes.Add(new CategoryAxis
                {
                    Position = AxisPosition.Left,
                    Key = "VerticalAxis",
                    ItemsSource = YAxisLabels,
                    MajorGridlineColor = OxyColors.Black,
                    MajorGridlineStyle = LineStyle.Solid,
                    IsZoomEnabled = false,
                    IsPanEnabled = false,
                    FontSize = 14,
                    TitleFontSize = 14
                });

                // Color axis
                plotModel.Axes.Add(new LinearColorAxis()
                {
                    Palette = myPalette,
                });

                var rand = new Random();
                var data = new double[YAxisLabels.Count, XAxisLabels.Count];
                for (int x = 0; x < XAxisLabels.Count; ++x)
                {
                    for (int y = 0; y < YAxisLabels.Count; ++y)
                    {
                        data[y, x] = rand.Next(0, 200) * (0.13876876848794587508758879 * (y + 1));
                    }
                }

                var heatMapSeries = new HeatMapSeries
                {
                    X0 = 0,
                    X1 = XAxisLabels.Count - 1,
                    Y0 = 0,
                    Y1 = YAxisLabels.Count - 1,
                    XAxisKey = "HorizontalAxis",
                    YAxisKey = "VerticalAxis",
                    RenderMethod = HeatMapRenderMethod.Bitmap,
                    Interpolate = true,
                    Data = data,
                    TrackerFormatString = "{3}: {4}\n{1}: {2}\n{5}: {6:N1}%",
                };

                plotModel.Series.Add(heatMapSeries);
            }




        }
    }
}
```


WPF:
```
<Window x:Class="WpfApp1.ShellView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:oxy="clr-namespace:OxyPlot.Wpf;assembly=OxyPlot.Wpf">

    <Grid Background="White">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <DockPanel Background="Purple" Grid.Column="0"/>
        <oxy:PlotView  x:Name="Plot00" Model="{Binding PlotModels[0]}" Grid.Row="0" Grid.Column="1" Margin="0,0,2.5,2.5">
            <oxy:PlotView.DefaultTrackerTemplate>
                <ControlTemplate>
                    <oxy:TrackerControl Position="{Binding Position}" LineExtents="{Binding PlotModel.PlotArea}" BorderBrush="Black" BorderThickness="1" Foreground="Black">
                        <oxy:TrackerControl.Content>
                            <TextBlock Text="{Binding}" Margin="7" />
                        </oxy:TrackerControl.Content>
                    </oxy:TrackerControl>
                </ControlTemplate>
            </oxy:PlotView.DefaultTrackerTemplate>
        </oxy:PlotView>
        <DockPanel Background="Purple" Grid.Column="2"/>
    </Grid>

</Window>
```

Again I cant't get the error if the window is in standard size. But if I scale the window down to about 30% I get the error when click and hold with the left mouse button to see the tracker, and the move the mouse to the top left ot top right corner.

If you can't produce it I can try to make a little video.

**Comment by VisualMelon** [comment] 2020-04-29 15:26
@UndisputedBasement33 thanks. I've reproduced it, and it seems to be fixed by adding some additional clamping in `GetValue` as in 7b8849e. Are you happy for me to commit the example to the example library?

**Comment by UndisputedBasement33** [comment] 2020-04-29 15:28
Yes of course.

**Comment by VisualMelon** [comment] 2020-04-29 16:41
The aforementione trivial solution is inadequate. The issue is that if, say, the heatmap data has dimensions `10 x 5`, and the tracker is placed at the far right size (x large), then the x value may be `9.5`. Without interpolation, this is rounded up to `10`, and `GetValue` dutifully looks for something with index `10`. Clamping is inadequate, because the tracker then believe it has found a meaningful piece of heatmap with index `10`, which is obviously nonsense.

**Closed** 2020-04-30 19:30 UTC
Labels: bug, series
