### ISSUE TITLE
Font family problem

### ISSUE THREAD

**Issue by V1rusFalcon** [oxyplot/oxyplot#1605] opened 2020-06-12 12:11 UTC
There is a problem with texts, see the images.

Linux
![Linux](https://user-images.githubusercontent.com/18369892/84501292-8abeb200-acb6-11ea-8ba9-a339f2b34a04.png)

Windows
![Windows](https://user-images.githubusercontent.com/18369892/84501312-94e0b080-acb6-11ea-8c2e-1f446c8be30f.png)

Make a simple chart and compile for linux-x64 and run it on linux.

Platform:
.NET version: .net core 3.1

**Comment by VisualMelon** [comment] 2020-06-12 12:17
Which platform/exporter are you using?

The default font is currently one that is Windows specific: have you tried any other fonts? `fc-list` may or may not be a helpful command (I'm not a regular Linux regular)

**Comment by V1rusFalcon** [comment] 2020-06-12 12:31
i'm using verdana and i've tried roboto which are installed on both machines. i'm using Oxyplot.core.drawing

**Comment by VisualMelon** [comment] 2020-06-12 12:48
Thanks. Could you let us know which version of OxyPlot you are using? I'll try to test this, but I seem to have messed up my WSL, so it might be a while.

**Comment by V1rusFalcon** [comment] 2020-06-12 13:00
oxyplot.core v2.0 and oxyplot.core.drawing v2.0

**Comment by VisualMelon** [comment] 2020-06-12 15:14
I've reproduced this in a WSL Ubuntu 20.04 instance using OxyPlot 2.0 and the current pre-release with .NET Core 3.1. It does not seem to occur with .NET Core 2.1. (same project, different framework).

I have no idea what is going on there, but I'll have another look over the weekend if I find the time.

**Comment by VisualMelon** [comment] 2020-06-12 16:01
Looks like this is resolved by advancing to System.Drawing.Common version 4.7.0. Just adding it to the consuming project seems to do the job (direct reference is favoured over the dependencies in `OxyPlot.Core.Drawing`).

    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />

Can you test this, and let me know if it works for you? If so, we can integrate the change into the library.

**Comment by V1rusFalcon** [comment] 2020-06-12 17:11
> ```
> <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
> ```
I just tried. It works!

**Closed** 2020-06-14 06:30 UTC
Labels: Core Drawing, bug
